import React from 'react';
import { CalendarClock, Droplets, Gauge, Thermometer, Waves } from 'lucide-react';

const rows = [
  { icon: Thermometer, element: 'Teplotní a vlhkostní senzor', action: 'Spustí mlžení až při vhodných podmínkách.', saving: 'Omezuje provoz v chladu, dešti a při vysoké vlhkosti, kdy se mlha odpařuje pomaleji.' },
  { icon: Droplets, element: 'Chytrý ventil', action: 'Přesně otevírá a uzavírá jednotlivé zóny.', saving: 'Zastaví průtok mimo aktivní zónu a eliminuje zbytečné čerpání vody.' },
  { icon: CalendarClock, element: 'Časový program', action: 'Řídí provoz podle vytížených hodin.', saving: 'Mlha běží jen v plánovaných časech provozu, ne po celý den bez kontroly.' },
  { icon: Gauge, element: 'Zónové řízení', action: 'Přizpůsobí intenzitu konkrétní části prostoru.', saving: 'Menší nebo méně vytížené zóny nepotřebují stejný průtok jako hlavní ochlazovaná plocha.' },
  { icon: Waves, element: 'Průběžná kontrola provozu', action: 'Umožní rychle reagovat na nestandardní chod.', saving: 'Pomáhá odhalit nevhodné nastavení dříve, než se promítne do dlouhodobé spotřeby a nákladů.' },
];

export default function TechSystemComparison() { return <section className="border-y border-slate-200 bg-slate-50 py-16 lg:py-24"><div className="site-container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Prvky chytrého systému</p><h2 className="mt-3 text-slate-950">Každý prvek má vliv na provozní úsporu.</h2><p className="mt-5 text-slate-600">Senzory a ventily nevytvářejí úsporu samy o sobě. Jejich přínos spočívá v tom, že systém zbytečně nemlží tam, kde ochlazení právě nemá efekt.</p></div><div className="mt-9 overflow-x-auto border border-slate-200 bg-white"><table className="min-w-[720px] w-full text-left"><thead className="bg-slate-950 text-white"><tr><th className="p-5 text-xs uppercase tracking-[.12em]">Prvek systému</th><th className="p-5 text-xs uppercase tracking-[.12em]">Co reálně řídí</th><th className="p-5 text-xs uppercase tracking-[.12em]">Dlouhodobý dopad</th></tr></thead><tbody>{rows.map(({ icon: Icon, element, action, saving }) => <tr key={element} className="border-t border-slate-200 align-top"><td className="p-5 font-semibold text-slate-950"><span className="flex items-center gap-3"><Icon size={20} className="text-[#0070F3]" />{element}</span></td><td className="p-5 text-sm leading-relaxed text-slate-600">{action}</td><td className="p-5 text-sm leading-relaxed text-slate-600">{saving}</td></tr>)}</tbody></table></div></div></section>; }