export const LOCALIZED_UI = {
  en: {
    exploreKicker: 'Explore the system', exploreTitle: 'One platform. Different project scales.', exploreText: 'Move between urban, residential, custom and smart-control solutions without leaving the English project flow.',
    cards: { catalog: 'All products', city: 'Urban cooling', garden: 'Garden & terrace', custom: 'Custom design', smart: 'Smart control', references: 'Projects' },
    flowKicker: 'Project workflow', flowTitle: 'From a site photo to a manufacturable solution.',
    steps: [['01', 'Send the site', 'A photo, plan or approximate dimensions are enough for the first review.'], ['02', 'Select the direction', 'We recommend a product family or the simplest realistic custom geometry.'], ['03', 'Visualize', 'We can verify scale, position and visual integration directly in the site image.'], ['04', 'Technical review', 'Connection, anchoring, geometry and operating logic are checked before quotation or production.']],
    smartKicker: 'Smart operation', smartTitle: 'Control schedules, valves and optional sensors from one operating concept.', smartText: 'Remote operation is an optional project layer. The exact valve, sensor and automation configuration is always selected for the hydraulic design and site requirements.', smartPills: ['Remote control', 'Scheduling', 'Optional sensors'],
    formKicker: 'Project enquiry', formTitle: 'Send the place. We will define the next step.', formText: 'Use this form for a non-binding project enquiry. A photo or drawing can be added later during the follow-up.', form: { fields: { name: 'Name', email: 'E-mail', phone: 'Phone', company: 'Company / municipality', message: 'Project description' }, placeholders: { message: 'Location, dimensions, intended use, preferred product or any constraints…' }, consent: 'I have read the privacy information and acknowledge processing of my contact details for this project enquiry.', privacy: 'Privacy information', submit: 'Send non-binding enquiry', sending: 'Sending…', successTitle: 'Enquiry received', successText: 'Thank you. Your project has been sent to the HolmTec team and the visualization/download flow remains available separately.', error: 'The enquiry could not be sent. Please try again.' },
    faqKicker: 'Technical answers', faqTitle: 'What project teams usually need to clarify first.',
  },
  de: {
    exploreKicker: 'System entdecken', exploreTitle: 'Eine Plattform für unterschiedliche Projektgrößen.', exploreText: 'Wechseln Sie zwischen Stadt, Garten, Sonderanfertigung und Smart-Steuerung innerhalb des deutschsprachigen Projektflusses.',
    cards: { catalog: 'Alle Produkte', city: 'Stadtkühlung', garden: 'Garten & Terrasse', custom: 'Sonderanfertigung', smart: 'Smart-Steuerung', references: 'Referenzen' },
    flowKicker: 'Projektablauf', flowTitle: 'Vom Standortfoto zur realisierbaren Lösung.',
    steps: [['01', 'Standort senden', 'Für die erste Prüfung reichen Foto, Plan oder ungefähre Abmessungen.'], ['02', 'Richtung wählen', 'Wir empfehlen eine Produktfamilie oder die einfachste realistisch produzierbare Sondergeometrie.'], ['03', 'Visualisieren', 'Maßstab, Position und Einbindung können direkt im Standortfoto geprüft werden.'], ['04', 'Technisch prüfen', 'Anschluss, Verankerung, Geometrie und Betriebslogik werden vor Angebot oder Fertigung abgestimmt.']],
    smartKicker: 'Smart-Betrieb', smartTitle: 'Zeitpläne, Ventile und optionale Sensoren in einem Betriebskonzept.', smartText: 'Fernsteuerung ist eine optionale Projektebene. Ventil, Sensorik und Automatisierung werden immer passend zur Hydraulik und zum Standort gewählt.', smartPills: ['Fernsteuerung', 'Zeitpläne', 'Optionale Sensoren'],
    formKicker: 'Projektanfrage', formTitle: 'Senden Sie den Ort. Wir definieren den nächsten Schritt.', formText: 'Das Formular dient einer unverbindlichen Projektanfrage. Fotos oder Zeichnungen können anschließend ergänzt werden.', form: { fields: { name: 'Name', email: 'E-Mail', phone: 'Telefon', company: 'Firma / Kommune', message: 'Projektbeschreibung' }, placeholders: { message: 'Standort, Abmessungen, Nutzung, gewünschtes Produkt oder besondere Anforderungen…' }, consent: 'Ich habe die Datenschutzinformationen gelesen und nehme die Verarbeitung meiner Kontaktdaten für diese Projektanfrage zur Kenntnis.', privacy: 'Datenschutzinformationen', submit: 'Unverbindliche Anfrage senden', sending: 'Wird gesendet…', successTitle: 'Anfrage erhalten', successText: 'Vielen Dank. Ihr Projekt wurde an das HolmTec-Team übermittelt.', error: 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.' },
    faqKicker: 'Technische Antworten', faqTitle: 'Was Projektteams meistens zuerst klären müssen.',
  },
  pl: {
    exploreKicker: 'Poznaj system', exploreTitle: 'Jedna platforma dla różnych skal projektu.', exploreText: 'Przechodź między rozwiązaniami miejskimi, ogrodowymi, indywidualnymi i smart bez opuszczania polskiej wersji projektu.',
    cards: { catalog: 'Wszystkie produkty', city: 'Chłodzenie miast', garden: 'Ogród i taras', custom: 'Na zamówienie', smart: 'Smart sterowanie', references: 'Realizacje' },
    flowKicker: 'Proces projektu', flowTitle: 'Od zdjęcia miejsca do rozwiązania możliwego do wykonania.',
    steps: [['01', 'Wyślij miejsce', 'Do pierwszej analizy wystarczy zdjęcie, plan lub przybliżone wymiary.'], ['02', 'Wybierz kierunek', 'Rekomendujemy rodzinę produktów albo najprostszą realną geometrię indywidualną.'], ['03', 'Wizualizacja', 'Sprawdzamy skalę, pozycję i integrację bezpośrednio na zdjęciu miejsca.'], ['04', 'Weryfikacja techniczna', 'Przyłącze, kotwienie, geometria i logika pracy są sprawdzane przed wyceną lub produkcją.']],
    smartKicker: 'Inteligentna eksploatacja', smartTitle: 'Harmonogramy, zawory i opcjonalne czujniki w jednym koncepcie sterowania.', smartText: 'Sterowanie zdalne jest opcjonalną warstwą projektu. Konfigurację zaworu, czujników i automatyki dobieramy do hydrauliki oraz wymagań miejsca.', smartPills: ['Sterowanie zdalne', 'Harmonogramy', 'Opcjonalne czujniki'],
    formKicker: 'Zapytanie projektowe', formTitle: 'Wyślij miejsce. Ustalimy kolejny krok.', formText: 'Formularz służy do niezobowiązującego zapytania projektowego. Zdjęcia lub rysunki można uzupełnić w dalszym kontakcie.', form: { fields: { name: 'Imię i nazwisko', email: 'E-mail', phone: 'Telefon', company: 'Firma / miasto / gmina', message: 'Opis projektu' }, placeholders: { message: 'Lokalizacja, wymiary, sposób użytkowania, preferowany produkt lub ograniczenia…' }, consent: 'Zapoznałem/am się z informacją o prywatności i przyjmuję do wiadomości przetwarzanie danych kontaktowych na potrzeby tego zapytania.', privacy: 'Informacja o prywatności', submit: 'Wyślij niezobowiązujące zapytanie', sending: 'Wysyłanie…', successTitle: 'Zapytanie otrzymane', successText: 'Dziękujemy. Projekt został przekazany zespołowi HolmTec.', error: 'Nie udało się wysłać zapytania. Spróbuj ponownie.' },
    faqKicker: 'Odpowiedzi techniczne', faqTitle: 'Co zespoły projektowe zwykle ustalają na początku.',
  },
  sk: {
    exploreKicker: 'Preskúmajte systém', exploreTitle: 'Jedna platforma pre rôzne mierky projektu.', exploreText: 'Prechádzajte medzi mestskými, záhradnými, atypickými a smart riešeniami v rámci slovenskej verzie webu.',
    cards: { catalog: 'Všetky produkty', city: 'Mestské chladenie', garden: 'Záhrada a terasa', custom: 'Na mieru', smart: 'Smart riadenie', references: 'Realizácie' },
    flowKicker: 'Proces projektu', flowTitle: 'Od fotografie miesta k reálne vyrobiteľnému riešeniu.',
    steps: [['01', 'Pošlite miesto', 'Na prvé posúdenie stačí fotografia, plán alebo približné rozmery.'], ['02', 'Vyberte smer', 'Odporučíme produktovú rodinu alebo najjednoduchšiu reálne vyrobiteľnú geometriu.'], ['03', 'Vizualizácia', 'Mierku, polohu a začlenenie overíme priamo vo fotografii priestoru.'], ['04', 'Technické overenie', 'Prípojku, kotvenie, geometriu a prevádzkovú logiku preveríme pred ponukou alebo výrobou.']],
    smartKicker: 'Inteligentná prevádzka', smartTitle: 'Harmonogramy, ventily a voliteľné senzory v jednom koncepte riadenia.', smartText: 'Diaľkové ovládanie je voliteľná vrstva projektu. Ventil, senzory a automatizáciu vždy volíme podľa hydrauliky a podmienok miesta.', smartPills: ['Diaľkové ovládanie', 'Harmonogramy', 'Voliteľné senzory'],
    formKicker: 'Projektová požiadavka', formTitle: 'Pošlite miesto. Navrhneme ďalší krok.', formText: 'Formulár slúži na nezáväznú projektovú požiadavku. Fotografie alebo výkresy môžete doplniť pri ďalšom kontakte.', form: { fields: { name: 'Meno', email: 'E-mail', phone: 'Telefón', company: 'Firma / mesto / obec', message: 'Opis projektu' }, placeholders: { message: 'Lokalita, rozmery, spôsob využitia, preferovaný produkt alebo obmedzenia…' }, consent: 'Oboznámil/a som sa s informáciami o ochrane súkromia a beriem na vedomie spracovanie kontaktných údajov pre túto požiadavku.', privacy: 'Informácie o súkromí', submit: 'Odoslať nezáväznú požiadavku', sending: 'Odosielam…', successTitle: 'Požiadavka prijatá', successText: 'Ďakujeme. Projekt bol odoslaný tímu HolmTec.', error: 'Požiadavku sa nepodarilo odoslať. Skúste to znova.' },
    faqKicker: 'Technické odpovede', faqTitle: 'Čo projektové tímy zvyčajne potrebujú objasniť ako prvé.',
  },
  it: {
    exploreKicker: 'Esplora il sistema', exploreTitle: 'Una piattaforma per diverse scale di progetto.', exploreText: 'Passa tra soluzioni urbane, garden, custom e smart mantenendo il percorso interamente in italiano.',
    cards: { catalog: 'Tutti i prodotti', city: 'Raffrescamento urbano', garden: 'Giardino e terrazza', custom: 'Su misura', smart: 'Controllo smart', references: 'Progetti' },
    flowKicker: 'Percorso di progetto', flowTitle: 'Dalla foto del luogo a una soluzione realmente producibile.',
    steps: [['01', 'Invia il luogo', 'Per la prima valutazione bastano foto, planimetria o dimensioni indicative.'], ['02', 'Scegli la direzione', 'Consigliamo una famiglia prodotto o la geometria custom più semplice e realistica.'], ['03', 'Visualizzazione', 'Verifichiamo scala, posizione e integrazione direttamente nella foto del sito.'], ['04', 'Verifica tecnica', 'Collegamento, ancoraggio, geometria e logica operativa vengono controllati prima del preventivo o della produzione.']],
    smartKicker: 'Gestione intelligente', smartTitle: 'Programmazione, valvole e sensori opzionali in un unico concetto operativo.', smartText: 'Il controllo remoto è una funzione progettuale opzionale. Valvola, sensori e automazione vengono scelti in base all’idraulica e ai requisiti del sito.', smartPills: ['Controllo remoto', 'Programmazione', 'Sensori opzionali'],
    formKicker: 'Richiesta di progetto', formTitle: 'Invia il luogo. Definiamo il passo successivo.', formText: 'Il modulo serve per una richiesta non vincolante. Foto e disegni possono essere aggiunti nel contatto successivo.', form: { fields: { name: 'Nome', email: 'E-mail', phone: 'Telefono', company: 'Azienda / comune', message: 'Descrizione del progetto' }, placeholders: { message: 'Località, dimensioni, utilizzo, prodotto preferito o vincoli…' }, consent: 'Ho letto le informazioni sulla privacy e prendo atto del trattamento dei dati di contatto per questa richiesta di progetto.', privacy: 'Informazioni sulla privacy', submit: 'Invia richiesta non vincolante', sending: 'Invio…', successTitle: 'Richiesta ricevuta', successText: 'Grazie. Il progetto è stato inviato al team HolmTec.', error: 'Impossibile inviare la richiesta. Riprova.' },
    faqKicker: 'Risposte tecniche', faqTitle: 'Cosa i team di progetto devono chiarire per prima cosa.',
  },
};

export function getLocalizedUi(locale) {
  return LOCALIZED_UI[locale] || LOCALIZED_UI.en;
}
