import React from 'react';
import Logo from '@/components/layout/Logo';

const LOGO_URL = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/314f4a3ac_mlzidla_logo_bez_pozadi.png';

export default function BrandLogoGuide() {
  return <div className="mt-16"><div className="max-w-2xl"><p className="font-mono text-xs uppercase tracking-[.16em] text-secondary">Logo</p><h3 className="mt-3 text-3xl">Podpis značky musí mít prostor.</h3><p className="mt-3 text-muted-foreground">Primární je horizontální sestava symbolu a názvu. V digitálním prostředí může logo použít jemný nástup a klidný pohyb symbolu.</p></div>
    <div className="mt-7 grid gap-4 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex min-h-64 items-center justify-center bg-brandwhite p-10"><img src={LOGO_URL} alt="Primární horizontální logo MLŽIDLA" className="max-h-24 max-w-full object-contain"/></div><div className="p-6"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-secondary">01 · Primární varianta</p><h4 className="mt-2 text-xl">Horizontální logo</h4><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Pro web, nabídky, tisk a značení. Minimální šířka 120 px na obrazovce a 30 mm v tisku.</p></div></article>
      <article className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex min-h-64 items-center justify-center bg-gradient-to-r from-primary via-slate-800 to-hydro p-10"><Logo/></div><div className="p-6"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-secondary">02 · Digitální varianta</p><h4 className="mt-2 text-xl">Animované logo</h4><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Jemný nástup a pomalý pohyb symbolu pro web nebo video. Bez rotace, skákání a výrazných efektů.</p></div></article></div>
    <div className="mt-4 grid gap-4 rounded-2xl border border-border bg-muted p-6 sm:grid-cols-3"><div><p className="font-semibold">Ochranná zóna</p><p className="mt-2 text-sm text-muted-foreground">Nejméně výška symbolu ze všech stran.</p></div><div><p className="font-semibold">Kontrast</p><p className="mt-2 text-sm text-muted-foreground">Pouze klidné světlé nebo tmavé pozadí.</p></div><div><p className="font-semibold">Zakázané úpravy</p><p className="mt-2 text-sm text-muted-foreground">Nedeformovat, nepřebarvovat a nepřidávat stíny.</p></div></div>
  </div>;
}