#!/usr/bin/env python3
"""
Hub Nabidky learning loop.

Builds a reusable learned-rules file for the Sales Hub skill from explicit
feedback and optional Firecrawl structured exports, then optionally packages
that skill into a distributable .skill archive.

Examples:
    python run-loop.py
    python run-loop.py --feedback .firecrawl/offer-feedback.json
    python run-loop.py --feedback feedback.json --package --output ./dist
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
DEFAULT_SKILL = ROOT / "skills" / "hub-nabidky-learning"
MANDATORY_RULE = "use null when unknown / do not infer"


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def flatten_feedback(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        for key in ("items", "feedback", "records", "data"):
            value = payload.get(key)
            if isinstance(value, list):
                return [item for item in value if isinstance(item, dict)]
        return [payload]
    return []


def normalize_text(value: Any) -> str:
    return " ".join(str(value or "").split()).strip()


def feedback_score(item: dict[str, Any]) -> tuple[int, int, str]:
    priority = int(item.get("priority") or 3)
    kind = normalize_text(item.get("feedback_type"))
    weights = {
        "critique": 50,
        "rejected_pattern": 45,
        "user_requirement": 40,
        "approved_pattern": 30,
        "result_outcome": 10,
    }
    return (priority, weights.get(kind, 0), normalize_text(item.get("category")))


def dedupe_feedback(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    result: list[dict[str, Any]] = []
    for item in sorted(items, key=feedback_score, reverse=True):
        if item.get("active") is False:
            continue
        text = normalize_text(item.get("lesson") or item.get("feedback_text"))
        if not text:
            continue
        fingerprint = text.casefold()
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        result.append({**item, "_lesson": text})
    return result


def summarize_firecrawl(paths: list[Path]) -> list[str]:
    notes: list[str] = []
    for path in paths:
        if not path.exists():
            continue
        try:
            payload = load_json(path)
        except Exception as exc:
            notes.append(f"- `{path.name}` could not be parsed: {exc}")
            continue

        if isinstance(payload, dict):
            keys = sorted(payload.keys())[:12]
            notes.append(
                f"- `{path.name}` loaded as structured research input. Top-level keys: "
                + ", ".join(f"`{key}`" for key in keys)
                + ". Treat missing technical fields as `null`; do not infer them."
            )
        elif isinstance(payload, list):
            notes.append(
                f"- `{path.name}` loaded with {len(payload)} records. Preserve source provenance; "
                "missing technical fields remain `null`."
            )
        else:
            notes.append(f"- `{path.name}` loaded. Do not infer missing technical values.")
    return notes


def build_learned_markdown(feedback: list[dict[str, Any]], research_notes: list[str]) -> str:
    by_category = Counter(normalize_text(item.get("category")) or "other" for item in feedback)
    lines = [
        "# Learned rules — Hub nabídky",
        "",
        "> Generated by `run-loop.py` from explicit feedback and structured research inputs.",
        "> This file contains preferences and reusable process rules, not independently verified product specifications.",
        "",
        "## Mandatory technical safeguard",
        "",
        f"- **{MANDATORY_RULE}**. Unknown technical values stay `null` and must never be guessed from context, imagery, competitor pages, or nearby products.",
        "- A learned preference must never override a verified product record, approved technical document, safety constraint, or explicit current-project requirement.",
        "",
    ]

    if feedback:
        lines.extend(["## Active learned feedback", ""])
        for item in feedback:
            category = normalize_text(item.get("category")) or "other"
            kind = normalize_text(item.get("feedback_type")) or "feedback"
            priority = int(item.get("priority") or 3)
            lines.append(f"- **P{priority} · {category} · {kind}:** {item['_lesson']}")
        lines.extend(["", "## Feedback coverage", ""])
        for category, count in sorted(by_category.items()):
            lines.append(f"- {category}: {count}")
        lines.append("")
    else:
        lines.extend([
            "## Active learned feedback",
            "",
            "- No external feedback export was supplied for this run. Runtime feedback remains stored in Base44 `OfferLearningFeedback`.",
            "",
        ])

    lines.extend(["## Structured research inputs", ""])
    lines.extend(research_notes or ["- No Firecrawl export found for this run."])
    lines.extend([
        "",
        "## Decision policy",
        "",
        "1. Current explicit project requirement wins over older preference rules.",
        "2. Technical truth and source-backed data win over style or sales optimization.",
        "3. Repeated criticism should become a stronger rule than a one-time approval signal.",
        "4. Commercial outcomes are supporting evidence only; do not infer causality from one approved or rejected offer.",
        "5. Never convert an unknown technical field into a guessed value merely to make a document look complete.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile Hub Nabidky learning feedback into a reusable skill.")
    parser.add_argument("--skill", type=Path, default=DEFAULT_SKILL, help="Skill folder containing SKILL.md")
    parser.add_argument("--feedback", type=Path, action="append", default=[], help="JSON feedback export; may be repeated")
    parser.add_argument("--research", type=Path, action="append", default=[], help="Structured Firecrawl JSON; may be repeated")
    parser.add_argument("--package", action="store_true", help="Package the skill after rebuilding LEARNED.md")
    parser.add_argument("--output", type=Path, default=ROOT / "dist", help="Package output directory")
    args = parser.parse_args()

    skill_path = args.skill.resolve()
    if not (skill_path / "SKILL.md").exists():
        print(f"ERROR: SKILL.md not found in {skill_path}", file=sys.stderr)
        return 1

    feedback_items: list[dict[str, Any]] = []
    for feedback_path in args.feedback:
        if not feedback_path.exists():
            print(f"WARNING: feedback file missing: {feedback_path}", file=sys.stderr)
            continue
        try:
            feedback_items.extend(flatten_feedback(load_json(feedback_path)))
        except Exception as exc:
            print(f"WARNING: could not read {feedback_path}: {exc}", file=sys.stderr)

    research_paths = list(args.research)
    if not research_paths:
        research_paths = [
            ROOT / ".firecrawl" / "pricing.json",
            ROOT / ".firecrawl" / "products.json",
            ROOT / ".firecrawl" / "features.json",
            ROOT / ".firecrawl" / "competitor-products.json",
        ]

    learned = dedupe_feedback(feedback_items)
    research_notes = summarize_firecrawl(research_paths)
    learned_path = skill_path / "LEARNED.md"
    learned_path.write_text(build_learned_markdown(learned, research_notes), encoding="utf-8")

    print(f"Updated: {learned_path}")
    print(f"Active learned rules: {len(learned)}")
    if research_notes:
        print(f"Structured research inputs: {len(research_notes)}")

    if args.package:
        args.output.mkdir(parents=True, exist_ok=True)
        command = [sys.executable, str(ROOT / "utils" / "package_skill.py"), str(skill_path), str(args.output)]
        result = subprocess.run(command, cwd=ROOT, check=False)
        return result.returncode

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
