import React from 'react';
import { ArrowRight, Cloud, Smartphone, Thermometer, Wind } from 'lucide-react';
import { Link } from 'react-router-dom';

const VIDEO_URL = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/0d9a4e147_mlznabranaGATE70-video.mp4';
const stats = [{ icon: Thermometer, value: 'až −9 °C', label: 'ochlazení' }, { icon: Cloud, value: 'až 18 m²', label: 'mlžný závoj' }, { icon: Wind, value: 'směr větru', label: 'řízení provozu' }];

export default function GateProductSmartPanel() {
  return <section className="bg-slate-950 py-20 text-white"><div className="site-container"><div className="mb-9 max-w-3xl"><p className="content-eyebrow mb-4 text-cyan">GATE v provozu</p><h2 className="content-title text-white">Mlžná brána se vším všudy.</h2><p className="mt-4 text-white/60">Video, klíčové provozní údaje a přístup k chytrému řízení na jednom místě.</p></div><div className="grid overflow-hidden border border-white/10 lg:grid-cols-[1.4fr_.6fr]"><div className="relative bg-black"><video src={VIDEO_URL} controls muted loop playsInline className="aspect-video h-full w-full object-cover" /><div className="pointer-events-none absolute left-4 top-4 border border-cyan/35 bg-slate-950/75 px-3 py-2 text-xs font-bold text-cyan backdrop-blur">GATE · LIVE</div></div><div className="flex flex-col justify-between bg-slate-900 p-6"><div className="space-y-3">{stats.map(({ icon: Icon, value, label }) => <div key={label} className="flex items-center gap-3 border-b border-white/10 pb-3"><Icon size={18} className="text-cyan" /><div><strong className="block text-sm">{value}</strong><span className="text-xs text-white/45">{label}</span></div></div>)}</div><div className="mt-7 space-y-3"><Link to="/aplikace-ovladani-mlzitek" className="flex items-center justify-between text-sm font-bold text-cyan">Aplikace a návody <Smartphone size={16} /></Link><Link to="/poptavka?produkt=Mlžná%20brána%20GATE" className="btn-metallic-mist w-full justify-center px-5 py-3 text-sm font-bold">Poptat řešení GATE <ArrowRight size={15} /></Link></div></div></div></div></section>;
}