import React, { useState } from 'react';
import { ArrowUpRight, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';

const filters = ['Vše', 'Města', 'Hotely', 'Parky', 'Restaurace', 'Soukromé projekty'];
const projects = [{ name: 'Městské ochlazení', place: 'Veřejný prostor', year: '2026', type: 'Města', product: 'City Line®' }, { name: 'Mlžná promenáda', place: 'Parkový areál', year: '2025', type: 'Parky', product: 'City Arc®' }, { name: 'Letní terasa', place: 'Hotel & gastro', year: '2025', type: 'Hotely', product: 'Garden Arc®' }];

export default function ReferenceShowcase() {
  const [active, setActive] = useState('Vše');
  const visible = active === 'Vše' ? projects : projects.filter((item) => item.type === active || (active === 'Restaurace' && item.type === 'Hotely'));
  return <section className="max-w-7xl mx-auto px-6 lg:px-8 py-20"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-7 mb-10"><div><p className="font-mono text-[11px] tracking-[0.18em] uppercase text-teal-700 mb-3">Realizace</p><h2 className="font-heading text-4xl lg:text-5xl text-slate-950">Prostory, které zvou ven.</h2></div><Link to="/poptavka" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950">Navrhnout vlastní projekt <ArrowUpRight size={17}/></Link></div><div className="flex gap-2 overflow-x-auto pb-5">{filters.map((item) => <button key={item} onClick={() => setActive(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-medium transition ${active === item ? 'bg-[#073142] text-white' : 'border border-slate-200 text-slate-600 hover:border-slate-400'}`}>{item}</button>)}</div><div className="grid md:grid-cols-3 gap-5">{visible.map((item) => <article key={item.name} className="group border border-slate-200 bg-white overflow-hidden"><div className="aspect-[4/3] overflow-hidden bg-slate-100"><img src="/media/placeholders/mist-scene.svg" alt={`Náhled realizace ${item.name}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-5"><div className="flex justify-between font-mono text-[10px] tracking-widest text-slate-500 uppercase"><span>{item.year}</span><span>{item.product}</span></div><h3 className="font-heading text-2xl mt-5 text-slate-950">{item.name}</h3><p className="flex items-center gap-1.5 text-sm text-slate-500 mt-2"><MapPin size={14}/>{item.place}</p><Link to="/poptavka" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-teal-800">Zobrazit případovou studii <ArrowUpRight size={15}/></Link></div></article>)}</div></section>;
}