export const COLLECTIONS = {
  city: {
    name: 'Městská mlžítka', label: 'Města, obce a veřejný prostor', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/da0942c09_mlzidla-mlzitka-pro-mesta-obce.png', video_url: 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/0d9a4e147_mlznabranaGATE70-video.mp4', headline: 'Městská mlžítka pro náměstí, parky a veřejný prostor.', text: 'Navrhujeme a vyrábíme odolná nerezová mlžítka pro města, obce, architekty a správce veřejných ploch. Od prvního návrhu přes technické řešení až po instalaci a servis.', sectionHeading: 'Spolehlivé řešení pro dlouhodobý veřejný provoz.', features: ['Návrh podle prostoru, pohybu lidí a provozních podmínek', 'Odolná nerezová konstrukce a servisovatelné technické řešení', 'Spolupráce s městy, projektanty, architekty i realizačními firmami'], includeAll: true, lastSlug: 'mlzici-tryska'
  },
  garden: {
    name: 'Zahradní mlžítka', label: 'Zahrady, terasy a venkovní posezení', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/b94c771e1_a982a794f_mlzitkosteblo.jpg', video_url: 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/feff82d99_Aura-mlzitko-video-01.MP4', headline: 'Zahradní mlžítka pro terasy, pergoly a místa, kde chcete zůstat déle.', text: 'Navrhujeme a vyrábíme nerezová mlžítka pro rodinné zahrady, terasy, pergoly i venkovní gastro a hotelové zóny. Čistý design, snadná obsluha a řešení instalace podle konkrétního prostoru.', sectionHeading: 'Komfortní ochlazení zahrady bez kompromisu v designu.', features: ['Nerezové provedení navržené pro dlouhodobý venkovní provoz', 'Pevná i dočasná instalace podle charakteru zahrady nebo terasy', 'Pomoc s výběrem modelu, umístěním, napojením a příslušenstvím'], productSlugs: ['mlzitko-bendy', 'aura-mlzitko', 'aura-garden-duo', 'spiralove-mlzitko', 'mlzitko-mrak', 'mlzitko-lizatko', 'ostrev-mlzitko', 'mlzna-brana-gate']
  },
  aura: {
    name: 'Kolekce AURA®', label: 'AURA® · město i zahrada', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/1e0142d25_Mlzitko-v-mestskem-parku-VDMA.jpg', video_url: 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/feff82d99_Aura-mlzitko-video-01.MP4', headline: 'Jeden kruhový motiv. Dvě prostředí. Čtyři základní konfigurace.', text: 'Kolekce AURA® rozděluje kruhové mlžítko do městské a zahradní řady. V obou je k dispozici samostatná varianta Single a dvojitá sestava Duo. Nízkotlaká mlha funguje přímo z vodovodního řádu bez vysokotlakého čerpadla.', sectionHeading: 'AURA® jako modulární kolekce pro zahradu i veřejný prostor.', features: ['AURA Garden Single / Duo pro terasy, zahrady a rezidenční zóny', 'AURA City Single / Duo pro parky, promenády, náměstí a veřejný prostor', 'AISI 316L, nízkotlaká mlha a přímé napojení na vodovodní řád'], productSlugs: ['aura-mlzitko', 'aura-garden-duo', 'aura-city-single', 'aura-city-duo']
  },
  bendy: {
    name: 'Kolekce BENDY®', label: 'BENDY® · město i zahrada', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/88c697962_generated_image.png', headline: 'Jedna křivka. Více způsobů, jak ochladit prostor.', text: 'Kolekce BENDY® vychází z ikonického ohnutého nerezového prvku a rozvíjí jej od samostatného mlžítka přes rodinu BENDY ARC 1.0 / 2.0 / 3.0 ve velikostech S / M / L až po 360° Back-to-Back a víceprvkovou Alej. Jednotlivé varianty lze navrhovat pro zahrady, náměstí, parky, promenády i sportoviště.', sectionHeading: 'BENDY® jako modulární systém pro různé měřítko prostoru.', features: ['Charakteristická organická křivka BENDY®', 'BENDY ARC 1.0 / 2.0 / 3.0 · každý ve velikostech S / M / L', 'Nerezové provedení a projektové nastavení trysek, kotvení a řízení'], productSlugs: ['mlzitko-bendy', 'bendy-arc', 'bendy-arc-2-0', 'bendy-arc-3-0', 'bendy-back-to-back', 'bendy-alej', 'brana-bendy']
  },
  ostrev: {
    name: 'Kolekce OSTREV City®', label: 'OSTREV City® · orientace i ochlazení', image: 'https://base44.app/api/apps/6a3ee88c10959cd3588c4d68/files/mp/public/6a3ee88c10959cd3588c4d68/cd22b84b0_1000000697.jpg', headline: 'Městské mlžítko, které může ukazovat cestu.', text: 'OSTREV City® spojuje organický stromový motiv, nízkotlaké mlžení a možnost orientačního systému na míru. Tři výškové varianty S / M / L lze doplnit o směrové šipky, názvy míst, vzdálenosti, pozdrav, slogan nebo identitu konkrétního města.', sectionHeading: 'Jedna silueta. Tři měřítka. Nekonečně mnoho městských příběhů.', features: ['OSTREV City S / M / L podle měřítka prostoru', 'Volitelný rozcestník: šipky, texty, názvy míst, vzdálenosti a uvítací sdělení', 'AISI 316L, nízkotlaká mlha a napojení přímo na vodovodní řád bez vysokotlakého čerpadla'], productSlugs: ['ostrev-city-s', 'ostrev-city-m', 'ostrev-city-l', 'ostrev-mlzitko']
  },
  art: {
    name: 'Autorská kolekce mlžítek', label: 'Autorské instalace', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/68953132b_IMG_3524.jpg', headline: 'Funkční objekt, který dává místu charakter.', text: 'Autorské mlžné skulptury pro veřejný prostor, vstupy, parky a projekty na míru.', sectionHeading: 'Mlha jako součást zážitku místa.', features: ['Organické tvary z nerezu', 'Individuální návrh a výroba', 'Mlha jako součást zážitku místa'], productSlugs: ['mlzitko-mrak', 'spiralove-mlzitko']
  }
};