export const COLLECTIONS = {
  city: {
    name: 'Městská kolekce mlžítek', label: 'Města, obce a veřejný prostor', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/da0942c09_mlzidla-mlzitka-pro-mesta-obce.png', video_url: 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/0d9a4e147_mlznabranaGATE70-video.mp4', headline: 'Mlžítka pro města, parky a prostory, kde se lidé potkávají.', text: 'Navrhujeme odolné nerezové mlžicí prvky pro obce, architekty a správce veřejných míst. Každé řešení zohledňuje pohyb lidí, provoz i charakter konkrétní lokality.', sectionHeading: 'Partner pro ochlazení veřejného prostoru.', features: ['Spolupráce s obcí, architektem i realizační firmou', 'Návrh rozměru, umístění a napojení podle lokality', 'Nerezová konstrukce pro dlouhodobý veřejný provoz'], includeAll: true, lastSlug: 'mlzici-tryska'
  },
  garden: {
    name: 'Zahradní kolekce mlžítek', label: 'Zahrady, terasy a gastro provozy', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/60eaadb9e_generated_image.png', video_url: 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/feff82d99_Aura-mlzitko-video-01.MP4', headline: 'Mlžítka pro zahrady a terasy, kde chcete zůstat déle.', text: 'Čisté nerezové tvary pro rodinné zahrady, pergoly, restaurační terasy a hotelové venkovní zóny. Jemná mlha zpříjemní horké dny bez mokrého povrchu.', sectionHeading: 'Rezidenční ochlazení v čistém nerezovém designu.', features: ['Ohýbané nerezové trubky o průměru 70 mm', 'Diskrétní řešení pro terasy, pergoly a zahradní posezení', 'Mobilní i pevná instalace podle vašeho exteriéru'], productSlugs: ['mlzitko-bendy', 'aura-mlzitko', 'spiralove-mlzitko', 'mlzitko-mrak', 'mlzitko-lizatko', 'ostrev-mlzitko', 'mlzna-brana-gate']
  },
  art: {
    name: 'Autorská kolekce mlžítek', label: 'Autorské instalace', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/68953132b_IMG_3524.jpg', headline: 'Funkční objekt, který dává místu charakter.', text: 'Autorské mlžné skulptury pro veřejný prostor, vstupy, parky a projekty na míru.', sectionHeading: 'Mlha jako součást zážitku místa.', features: ['Organické tvary z nerezu', 'Individuální návrh a výroba', 'Mlha jako součást zážitku místa'], productSlugs: ['mlzitko-mrak', 'spiralove-mlzitko']
  }
};