import { CloudFog, DoorOpen, Waves, ShowerHead, Package, Thermometer, Droplet, Gauge, Zap, Plug, ShieldCheck } from 'lucide-react';

export const PRODUCTS = [
  {
    id: 'mrak',
    name: 'MRÁK',
    short: 'Interaktivní mlžná socha',
    icon: CloudFog,
    category: 'Interaktivní mlžná socha',
    categoryGroup: 'Interaktivní mlžné sochy',
    description: 'Designový mlžný prvek z nerezové oceli vytvářející jemnou vodní mlhu pro ochlazení, hru i vizuální efekt.',
    description2: 'Ideální pro dětská hřiště, parky, náměstí, zoologické zahrady a veřejné prostory.',
    longDescription: 'Interaktivní mlžná socha MRÁK vytváří jemnou aerosoli z mikrokapek vody, která přináší příjemné ochlazení a jedinečný vizuální efekt. Děti i dospělí si užijí zábavu v bezpečném prostředí bez chemie. Konstrukce z kvalitní nerezové oceli zaručuje dlouhou životnost a odolnost vůči povětrnostním vlivům. Systém je plně automatizovaný a navržen pro snadný provoz i údržbu. Možnost doplnění o RGB LED osvětlení pro ještě větší zážitek.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/7016348c6_generated_image.png',
    gallery: [
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/7016348c6_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f436db8ab_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/0549d625f_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
    ],
    quickSpecs: [
      { icon: Thermometer, label: 'Ochlazení', value: 'až o 10 °C' },
      { icon: Droplet, label: 'Spotřeba vody', value: 'od 1,2 l/min' },
      { icon: Gauge, label: 'Tlak vody', value: '3–8 bar' },
      { icon: Zap, label: 'Příkon systému', value: 'od 0,75 kW' },
      { icon: Plug, label: 'Napájení', value: '230 V / 50 Hz' },
      { icon: ShieldCheck, label: 'Záruka', value: '24 měsíců' },
    ],
    suitableFor: ['Dětská hřiště a vodní světy', 'Městské parky a náměstí', 'Zoologické a botanické zahrady', 'Nákupní centra a komerční prostory', 'Hotely, resorty a wellness areály'],
    dimensions: { height: '3050 mm', width: '3400 mm', depth: '450 mm' },
    baseParams: [
      { label: 'Výška', value: '3050 mm' }, { label: 'Šířka', value: '3400 mm' }, { label: 'Hloubka', value: '450 mm' },
      { label: 'Materiál', value: 'Nerezová ocel AISI 304 / 316' }, { label: 'Povrchová úprava', value: 'Broušená / leštěná' },
      { label: 'Trysky', value: 'Nerezové nízkotlaké' }, { label: 'Tlak vody', value: '3–8 bar' },
      { label: 'Spotřeba vody', value: '1,2–2,5 l/min' }, { label: 'Příkon', value: '0,75–1,5 kW' },
      { label: 'Napájení', value: '230 V / 50 Hz' }, { label: 'Ovládání', value: 'Automatické' }, { label: 'Provozní teplota', value: '+5 °C až +40 °C' },
    ],
  },
  {
    id: 'brana',
    name: 'MLŽNÁ BRÁNA',
    short: 'Designový mlžný průchod',
    icon: DoorOpen,
    category: 'Designový mlžný průchod',
    categoryGroup: 'Mlžné brány',
    description: 'Architektonická mlžná brána z nerezové oceli — návštěvník jí doslova prochází skrz jemnou mlžnou stěnu.',
    description2: 'Vhodná pro vstupy na eventy, náměstí, obchodní centra i firemní areály.',
    longDescription: 'Mlžná brána vytváří dramatický vstupní zážitek — návštěvník prochází zdí jemné mlhy vytvořené řadou nerezových trysek po obvodu rámu. Čisté architektonické linie z broušené nerezové oceli zapadnou do moderního i historického prostředí. Systém je automaticky řízen časovým nebo pohybovým čidlem a lze jej doplnit o RGB podsvícení pro noční provoz.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/17e1fc843_MlznabranaGATE70U.png',
    gallery: [
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/17e1fc843_MlznabranaGATE70U.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f6eb8b2ea_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f436db8ab_generated_image.png',
    ],
    quickSpecs: [
      { icon: Thermometer, label: 'Ochlazení', value: 'až o 8 °C' },
      { icon: Droplet, label: 'Spotřeba vody', value: 'od 2 l/min' },
      { icon: Gauge, label: 'Tlak vody', value: '3–8 bar' },
      { icon: Zap, label: 'Příkon systému', value: 'od 1,1 kW' },
      { icon: Plug, label: 'Napájení', value: '230 V / 50 Hz' },
      { icon: ShieldCheck, label: 'Záruka', value: '24 měsíců' },
    ],
    suitableFor: ['Vstupy na eventy a festivaly', 'Náměstí a veřejné prostory', 'Obchodní centra a showroomy', 'Sportovní areály'],
    dimensions: { height: '2400 mm', width: '3000 mm', depth: '300 mm' },
    baseParams: [
      { label: 'Výška', value: '2400 mm' }, { label: 'Šířka', value: '3000 mm' }, { label: 'Hloubka', value: '300 mm' },
      { label: 'Materiál', value: 'Nerezová ocel AISI 304 / 316' }, { label: 'Povrchová úprava', value: 'Broušená / leštěná' },
      { label: 'Trysky', value: 'Nerezové nízkotlaké' }, { label: 'Tlak vody', value: '3–8 bar' },
      { label: 'Spotřeba vody', value: '2–3,5 l/min' }, { label: 'Příkon', value: '1,1–1,8 kW' },
      { label: 'Napájení', value: '230 V / 50 Hz' }, { label: 'Ovládání', value: 'Automatické' }, { label: 'Provozní teplota', value: '+5 °C až +40 °C' },
    ],
  },
  {
    id: 'linie',
    name: 'MLŽNÁ LINIE',
    short: 'Lineární mlžný systém',
    icon: Waves,
    category: 'Lineární mlžný systém',
    categoryGroup: 'Mlžné linie',
    description: 'Lineární nerezové potrubí s řadou trysek pro plošné ochlazení chodníků, teras a promenád.',
    description2: 'Snadná instalace podél zdí, pergol i lemů hřišť.',
    longDescription: 'Mlžná linie je modulární nerezové potrubí osazené řadou nízkotlakých trysek, které rovnoměrně rozptylují jemnou mlhu podél celé délky instalace. Systém lze libovolně prodlužovat po jednotlivých modulech a přizpůsobit tak přesně tvaru terasy, promenády nebo dětského hřiště. Montáž je možná na zeď, strop i samostatnou konstrukci.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/56eb29c84_generated_image.png',
    gallery: [
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/56eb29c84_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f6eb8b2ea_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/0549d625f_generated_image.png',
    ],
    quickSpecs: [
      { icon: Thermometer, label: 'Ochlazení', value: 'až o 7 °C' },
      { icon: Droplet, label: 'Spotřeba vody', value: 'od 1,5 l/min/m' },
      { icon: Gauge, label: 'Tlak vody', value: '3–8 bar' },
      { icon: Zap, label: 'Příkon systému', value: 'od 0,55 kW' },
      { icon: Plug, label: 'Napájení', value: '230 V / 50 Hz' },
      { icon: ShieldCheck, label: 'Záruka', value: '24 měsíců' },
    ],
    suitableFor: ['Terasy restaurací a kaváren', 'Chodníky a promenády', 'Pergoly a zahrady', 'Sportovní tribuny'],
    dimensions: { height: '300 mm', width: '2000 mm / modul', depth: '200 mm' },
    baseParams: [
      { label: 'Výška', value: '300 mm' }, { label: 'Šířka modulu', value: '2000 mm' }, { label: 'Hloubka', value: '200 mm' },
      { label: 'Materiál', value: 'Nerezová ocel AISI 304' }, { label: 'Povrchová úprava', value: 'Broušená' },
      { label: 'Trysky', value: 'Nerezové, anti-drip' }, { label: 'Tlak vody', value: '3–8 bar' },
      { label: 'Spotřeba vody', value: '1,5–2 l/min/m' }, { label: 'Příkon', value: '0,55–0,9 kW' },
      { label: 'Napájení', value: '230 V / 50 Hz' }, { label: 'Ovládání', value: 'Časové / pohybové čidlo' }, { label: 'Provozní teplota', value: '+5 °C až +40 °C' },
    ],
  },
  {
    id: 'tryska',
    name: 'MLŽNÁ TRYSKA',
    short: 'Nízkotlaká tryska',
    icon: ShowerHead,
    category: 'Nízkotlaká tryska',
    categoryGroup: 'Mlžné trysky',
    description: 'Nerezová nízkotlaká tryska HT-LT rozptylující mikro-kapky 5–10 µm, které se odpaří dřív, než dopadnou.',
    description2: 'Základní stavební prvek každé mlžné instalace HolmTec.',
    longDescription: 'Tryska HT-LT je precizně obráběný nerezový komponent tvořící základ všech mlžných instalací HolmTec. Díky provoznímu tlaku 3–8 bar rozptyluje vodu na mikro-kapky o velikosti 5–10 µm, které se odpaří dříve, než dopadnou na zem — výsledkem je suchá, příjemně chladivá mlha bez pocitu mokra. Tryska je vybavena systémem anti-drip proti odkapávání.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
    gallery: [
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f436db8ab_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/0549d625f_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/17e1fc843_MlznabranaGATE70U.png',
    ],
    quickSpecs: [
      { icon: Thermometer, label: 'Ochlazení', value: 'až o 6 °C' },
      { icon: Droplet, label: 'Spotřeba vody', value: 'od 0,3 l/min' },
      { icon: Gauge, label: 'Tlak vody', value: '3–8 bar' },
      { icon: Zap, label: 'Kapka', value: '5–10 µm' },
      { icon: Plug, label: 'Připojení', value: 'Rychlospojka 1/2"' },
      { icon: ShieldCheck, label: 'Záruka', value: '24 měsíců' },
    ],
    suitableFor: ['Doplnění stávajících mlžných systémů', 'Individuální instalace na míru', 'Servis a náhradní díly'],
    dimensions: { height: '120 mm', width: '40 mm', depth: '40 mm' },
    baseParams: [
      { label: 'Výška', value: '120 mm' }, { label: 'Šířka', value: '40 mm' }, { label: 'Hloubka', value: '40 mm' },
      { label: 'Materiál', value: 'Nerezová ocel AISI 316' }, { label: 'Povrchová úprava', value: 'Leštěná' },
      { label: 'Velikost kapky', value: '5–10 µm' }, { label: 'Tlak vody', value: '3–8 bar' },
      { label: 'Spotřeba vody', value: '0,3–0,5 l/min' }, { label: 'Připojení', value: 'Rychlospojka 1/2"' },
      { label: 'Ovládání', value: '—' }, { label: 'Provozní teplota', value: '+5 °C až +40 °C' },
    ],
  },
  {
    id: 'stojan',
    name: 'MLŽNÝ STOJAN',
    short: 'Mobilní mlžný systém',
    icon: Package,
    category: 'Mobilní mlžný systém',
    categoryGroup: 'Mobilní mlžítka',
    description: 'Samostatně stojící mobilní mlžný sloup — bez nutnosti zemních prací, ideální pro eventy a sezónní provoz.',
    description2: 'Rychlá instalace i přesun mezi lokacemi během několika minut.',
    longDescription: 'Mlžný stojan je volně stojící nerezový sloup s integrovaným čerpadlem a řadou trysek, který lze umístit kdekoliv bez zemních prací. Ideální pro sezónní provozy, eventy a festivaly, kde je potřeba rychlá instalace i přesun. K dispozici s připojením na běžný rozvod vody a elektřiny, případně se solárním modulem pro nezávislý provoz.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/4ba44ac78_generated_image.png',
    gallery: [
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/4ba44ac78_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f6eb8b2ea_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/f436db8ab_generated_image.png',
      'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/0549d625f_generated_image.png',
    ],
    quickSpecs: [
      { icon: Thermometer, label: 'Ochlazení', value: 'až o 9 °C' },
      { icon: Droplet, label: 'Spotřeba vody', value: 'od 1,8 l/min' },
      { icon: Gauge, label: 'Tlak vody', value: '3–8 bar' },
      { icon: Zap, label: 'Příkon systému', value: 'od 0,75 kW' },
      { icon: Plug, label: 'Napájení', value: '230 V / solár' },
      { icon: ShieldCheck, label: 'Záruka', value: '24 měsíců' },
    ],
    suitableFor: ['Eventy a festivaly', 'Sezónní provozy', 'Mobilní chlazení bez stavebních prací', 'Firemní akce'],
    dimensions: { height: '1900 mm', width: '400 mm', depth: '400 mm' },
    baseParams: [
      { label: 'Výška', value: '1900 mm' }, { label: 'Šířka', value: '400 mm' }, { label: 'Hloubka', value: '400 mm' },
      { label: 'Materiál', value: 'Nerezová ocel AISI 304' }, { label: 'Povrchová úprava', value: 'Broušená' },
      { label: 'Trysky', value: 'Nerezové nízkotlaké' }, { label: 'Tlak vody', value: '3–8 bar' },
      { label: 'Spotřeba vody', value: '1,8–2,5 l/min' }, { label: 'Příkon', value: '0,75 kW' },
      { label: 'Napájení', value: '230 V / solární modul' }, { label: 'Ovládání', value: 'Automatické' }, { label: 'Provozní teplota', value: '+5 °C až +40 °C' },
    ],
  },
];