import { CloudFog, DoorOpen, Waves, ShowerHead, Package } from 'lucide-react';

export const PRODUCTS = [
  {
    id: 'mrak',
    name: 'MRÁK',
    short: 'Interaktivní mlžná socha',
    icon: CloudFog,
    category: 'Interaktivní mlžná socha',
    description: 'Designový mlžný prvek z nerezové oceli vytvářející jemnou vodní mlhu pro ochlazení, hru i vizuální efekt.',
    description2: 'Ideální pro dětská hřiště, parky, náměstí, zoologické zahrady a veřejné prostory.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/7016348c6_generated_image.png',
  },
  {
    id: 'brana',
    name: 'MLŽNÁ BRÁNA',
    short: 'Designový mlžný průchod',
    icon: DoorOpen,
    category: 'Designový mlžný průchod',
    description: 'Architektonická mlžná brána z nerezové oceli — návštěvník jí doslova prochází skrz jemnou mlžnou stěnu.',
    description2: 'Vhodná pro vstupy na eventy, náměstí, obchodní centra i firemní areály.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/17e1fc843_MlznabranaGATE70U.png',
  },
  {
    id: 'linie',
    name: 'MLŽNÁ LINIE',
    short: 'Lineární mlžný systém',
    icon: Waves,
    category: 'Lineární mlžný systém',
    description: 'Lineární nerezové potrubí s řadou trysek pro plošné ochlazení chodníků, teras a promenád.',
    description2: 'Snadná instalace podél zdí, pergol i lemů hřišť.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/56eb29c84_generated_image.png',
  },
  {
    id: 'tryska',
    name: 'MLŽNÁ TRYSKA',
    short: 'Vysokotlaká tryska',
    icon: ShowerHead,
    category: 'Vysokotlaká tryska',
    description: 'Nerezová vysokotlaká tryska HT-LT rozptylující mikro-kapky 5–10 µm, které se odpaří dřív, než dopadnou.',
    description2: 'Základní stavební prvek každé mlžné instalace HolmTec.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/6b51ec82a_19dca9db2_Social_Media_Video_Ads_A_close-up_captures_numerous_water_droplets_OIctonFe.png',
  },
  {
    id: 'stojan',
    name: 'MLŽNÝ STOJAN',
    short: 'Mobilní mlžný systém',
    icon: Package,
    category: 'Mobilní mlžný systém',
    description: 'Samostatně stojící mobilní mlžný sloup — bez nutnosti zemních prací, ideální pro eventy a sezónní provoz.',
    description2: 'Rychlá instalace i přesun mezi lokacemi během několika minut.',
    image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/4ba44ac78_generated_image.png',
  },
];