import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Instagram, Linkedin, Youtube, ArrowRight } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import Logo from '@/components/layout/Logo';

const columns = [{ title: 'Produkty', links: [['City Collection', '/mlzidla-mlzitka'], ['Garden Collection', '/mlzidla-mlzitka'], ['Zakázková řešení', '/poptavka']] }, { title: 'Realizace', links: [['Města a obce', '/reference'], ['Parky', '/reference'], ['Hotely a gastro', '/reference']] }, { title: 'Ke stažení', links: [['Katalog', '/ke-stazeni'], ['Technické listy', '/ke-stazeni'], ['CAD / BIM', '/ke-stazeni']] }, { title: 'Podpora', links: [['Brand identity', '/brand-identity'], ['Jak to funguje', '/technologie'], ['Servis', '/servis-udrzba'], ['Časté dotazy', '/podpora']] }, { title: 'Kontakt', links: [['Popsat projekt', '/poptavka'], ['O nás', '/o-nas'], ['Kontakt', '/kontakt']] }];

export default function Footer() {
  const [email, setEmail] = useState('');
  const [subscribed, setSubscribed] = useState(false);
  const subscribe = async (event) => {event.preventDefault();await base44.entities.NewsletterLead.create({ email, source: 'footer' });setSubscribed(true);};
  return <footer className="bg-primary text-primary-foreground"><div className="max-w-7xl mx-auto px-6 lg:px-8 pt-16 pb-8"><div className="grid lg:grid-cols-[1.5fr_repeat(5,1fr)] gap-10"><div><div className="inline-flex rounded border px-3 py-2 border-white/0 bg-white/0"><Logo size="sm" /></div><p className="mt-5 max-w-xs text-sm leading-relaxed text-white/65">Česká mlžítka a mlžné systémy na míru. Od návrhu a výroby po instalaci a servis.</p><div className="mt-6 flex gap-3"><a href="https://www.instagram.com/mlzne_sochy" aria-label="Instagram" className="text-white/70 hover:text-cyan"><Instagram size={18} /></a><a href="#linkedin" aria-label="LinkedIn" className="text-white/70 hover:text-cyan"><Linkedin size={18} /></a><a href="#youtube" aria-label="YouTube" className="text-white/70 hover:text-cyan"><Youtube size={18} /></a></div></div>{columns.map((column) => <div key={column.title}><p className="font-mono text-[10px] tracking-[.16em] uppercase text-cyan mb-5">{column.title}</p><div className="space-y-3">{column.links.map(([label, to]) => <Link key={label} to={to} className="block text-white/65 hover:text-white text-sm">{label}</Link>)}</div></div>)}</div><div className="mt-14 border-y border-white/10 py-7 flex flex-col md:flex-row gap-5 items-center justify-between"><div><p className="font-heading text-2xl">20 let zkušeností. Jedno dokonalé klima pro váš prostor.</p><p className="mt-1 text-sm text-white/60">Novinky z realizací a technologie, které dávají smysl.</p></div><form onSubmit={subscribe} className="flex w-full md:w-auto">{subscribed ? <p className="py-3 text-sm text-cyan">Děkujeme za váš zájem.</p> : <><input required value={email} onChange={(event) => setEmail(event.target.value)} aria-label="E-mail pro newsletter" type="email" placeholder="Váš e-mail" className="min-w-0 bg-white/10 px-4 py-3 text-sm text-white placeholder:text-white/45 outline-none" /><button className="bg-cyan px-4 text-slate-950" aria-label="Přihlásit k odběru"><ArrowRight size={18} /></button></>}</form></div><div className="pt-8 flex flex-col md:flex-row gap-3 justify-between text-xs text-white/45"><p>© {new Date().getFullYear()} MLŽIDLA® / HolmTec s.r.o.</p><div className="flex gap-4"><Link to="/gdpr">GDPR</Link><Link to="/gdpr">Cookies</Link><span>Certifikace</span></div></div></div></footer>;}