import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const usageLinks = [
  ['Města a obce', 'Chladnější veřejný prostor.', '/vyuziti/mesta-obce'], ['Parky a hřiště', 'Bezpečné letní osvěžení.', '/vyuziti/parky-hriste'], ['Koupaliště a aquaparky', 'Komfort kolem vody.', '/vyuziti/koupaliste'], ['Pro architekty', 'Mlha jako materiál návrhu.', '/vyuziti/architekti'], ['Komerční prostory', 'Pohodlí, které podporuje provoz.', '/vyuziti/komercni'], ['Eventy a festivaly', 'Osvěžení, na které se vzpomíná.', '/vyuziti/eventy'], ['Outdoor a zahrady', 'Chladivá oáza venku.', '/vyuziti/outdoor-zahrady'], ['Art instalace', 'Zakázkové mlžné skulptury.', '/vyuziti/art-instalace'], ['Školy, školky a děti', 'Jemné a bezpečné ochlazení.', '/vyuziti/skoly-skolky-deti'],
];
const benefitLinks = [
  ['Zvýšení tržeb a prodeje', 'Pro gastro, retail a eventy.', '/prinosy-mlzitek/zvyseni-trzeb-a-prodeje'], ['Automatizace provozu', 'SMART APP, meteočidla a eco režim.', '/prinosy-mlzitek/automatizace-provozu'], ['Zabezpečení a shoda', 'Hygiena, filtrace a dohled.', '/prinosy-mlzitek/zabezpeceni-a-shoda'], ['Nižší provozní náklady', 'Úspora vody, energie i času.', '/prinosy-mlzitek/snizovani-provoznich-nakladu'],
];
function MegaPanel({ title, intro, links, to }) { return <div className="absolute left-0 top-full w-[560px] bg-white border border-slate-200 shadow-2xl shadow-slate-950/20 p-5 text-slate-900"><Link to={to} className="block border-b border-slate-200 pb-4 mb-3"><p className="font-heading text-xl font-medium">{title} →</p><p className="text-sm leading-relaxed text-slate-500 mt-1">{intro}</p></Link><div className="grid grid-cols-2 gap-1">{links.map(([label, description, path]) => <Link key={path} to={path} className="p-3 hover:bg-slate-50 transition-colors"><p className="text-sm font-semibold">{label}</p><p className="text-xs leading-relaxed text-slate-500 mt-1">{description}</p></Link>)}</div></div>; }

export default function HeaderNav() {
  const [open, setOpen] = useState('');
  const [word, setWord] = useState('mlžení');
  const [finished, setFinished] = useState(false);
  useEffect(() => { if (open !== 'technology' || finished) return undefined; const first = setTimeout(() => setWord('ochlazování'), 1000); const second = setTimeout(() => { setWord('osvěžování'); setFinished(true); }, 4300); return () => { clearTimeout(first); clearTimeout(second); }; }, [open, finished]);
  return <nav className="hidden lg:block flex-1 min-w-0"><ul className="flex items-center gap-0.5 text-[13px] text-white/85 whitespace-nowrap">
    <li className="relative" onMouseEnter={() => setOpen('technology')} onMouseLeave={() => setOpen('')}><Link to="/jak-funguje-mlzeni" className="inline-flex px-3 py-3 font-medium hover:text-white">Jak <span className="ml-1 font-bold text-cyan transition-all duration-300">{word}</span><span className="ml-1">funguje?</span></Link>{open === 'technology' && <div className="absolute left-0 top-full w-[450px] p-5 bg-white border border-slate-200 shadow-2xl shadow-slate-950/20 text-slate-900"><Link to="/jak-funguje-mlzeni" className="block"><h3 className="font-heading text-xl font-medium mb-2">Jak <span className="text-sky-600">{word}</span> funguje? →</h3><p className="text-sm leading-relaxed text-slate-500">Technologie HolmTec mění vodu na jemnou mikro-mlhu pro přirozené ochlazení bez louží.</p></Link><div className="mt-4 pt-4 border-t border-slate-200 flex gap-5"><Link to="/smart-ovladani" className="text-xs font-semibold text-slate-600 hover:text-sky-600">SMART APP řízení</Link><Link to="/prinosy-mlzitek/zabezpeceni-a-shoda" className="text-xs font-semibold text-slate-600 hover:text-sky-600">UV-C filtrace a hygiena</Link></div></div>}</li>
    <li><Link to="/katalog" className="inline-flex px-3 py-3 hover:text-white">Produkty</Link></li>
    <li className="relative" onMouseEnter={() => setOpen('benefits')} onMouseLeave={() => setOpen('')}><Link to="/prinosy-mlzitek" className="inline-flex px-3 py-3 hover:text-white">Přínosy mlžítek</Link>{open === 'benefits' && <MegaPanel title="Přínosy mlžítek" intro="Čtyři konkrétní důvody, proč mlžení funguje pro provoz i rozpočet." links={benefitLinks} to="/prinosy-mlzitek" />}</li>
    <li><Link to="/reference" className="inline-flex px-3 py-3 hover:text-white">Realizace</Link></li>
    <li><Link to="/blog" className="inline-flex px-3 py-3 hover:text-white">Novinky</Link></li>
    <li><Link to="/podpora" className="inline-flex items-center px-3 py-3 hover:text-emerald-300"><span className="relative flex w-2.5 h-2.5 mr-2"><span className="absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-70 animate-ping"/><span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]"/></span>Podpora a servis</Link></li>
    <li className="ml-auto"><Link to="/partnerstvi" className="inline-flex px-3 py-3 text-xs text-white/70 hover:text-white">B2B Partnerství</Link></li>
    <li className="relative" onMouseEnter={() => setOpen('usage')} onMouseLeave={() => setOpen('')}><Link to="/vyuziti" className="inline-flex px-3 py-3 hover:text-white">Využití <small className="ml-1 text-[9px] text-white/55">B2B</small></Link>{open === 'usage' && <MegaPanel title="Využití mlžítek" intro="Řešení pro konkrétní typ prostoru a jeho provoz." links={usageLinks} to="/vyuziti" />}</li>
    <li><Link to="/poptavka" className="inline-flex px-3 py-2 border border-sky-400 text-sky-300 font-bold uppercase tracking-wide text-[11px] hover:bg-sky-400/10">Rychlá poptávka</Link></li><li><Link to="/kontakt" className="inline-flex px-3 py-2 bg-sky-500 text-white font-bold uppercase tracking-wide text-[11px] shadow-[0_4px_14px_rgba(14,165,233,.45)] hover:bg-sky-600">Kontakt</Link></li>
  </ul></nav>;
}