import React from 'react';
import { Link } from 'react-router-dom';
import { Building2, Cable, CalendarDays, Flower2, HeartPulse, Hotel, Landmark, Palette, Palmtree, School, Store, TentTree, Trees, Waves } from 'lucide-react';

const CATEGORIES = [
  { label: 'Města a obce', to: '/vyuziti/mesta-obce', icon: Building2 }, { label: 'Parky a hřiště', to: '/vyuziti/parky-hriste', icon: Trees }, { label: 'Školy, školky a děti', to: '/vyuziti/skoly-skolky-deti', icon: School }, { label: 'Domovy seniorů', to: '/vyuziti/domovy-senioru', icon: HeartPulse }, { label: 'Hotely a restaurace', to: '/vyuziti/hotely', icon: Hotel }, { label: 'Wellness terasy', to: '/vyuziti/wellness-terasy', icon: Waves }, { label: 'Koupaliště a aquaparky', to: '/vyuziti/koupaliste', icon: Palmtree }, { label: 'Pro architekty', to: '/vyuziti/architekti', icon: Landmark }, { label: 'Komerční prostory', to: '/vyuziti/komercni', icon: Store }, { label: 'Eventy a festivaly', to: '/vyuziti/eventy', icon: CalendarDays }, { label: 'Outdoor a zahrady', to: '/vyuziti/outdoor-zahrady', icon: Flower2 }, { label: 'Art instalace', to: '/vyuziti/art-instalace', icon: Palette },
];

const SOLUTIONS = [
  { label: 'Designová architektonická mlžítka', text: 'Zakázkové mlžné prvky pro veřejný prostor.', to: '/reseni/designova', icon: Landmark }, { label: 'Vstupní a uvítací mlžné brány', text: 'Výrazný vstup a osvěžení návštěvníků.', to: '/reseni/brany', icon: Building2 }, { label: 'Chytré moduly a příslušenství', text: 'Snímače, ventily, aplikace a přehled provozu.', to: '/reseni/chytre-moduly', icon: Cable }, { label: 'Mobilní eventová mlžítka – pronájem', text: 'Rychle připravené řešení pro krátkodobé akce.', to: '/reseni/mobilni-eventove', icon: TentTree },
];

export default function ProductMegaMenu() {
  return <div className="absolute left-0 top-full w-[1020px] rounded-b-2xl border border-slate-200 bg-white p-6 text-slate-900 shadow-2xl shadow-slate-950/20"><div className="flex items-end justify-between border-b border-slate-100 pb-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Produkty a řešení</p><p className="mt-1 text-sm text-slate-500">Vyberte prostor nebo typ řešení.</p></div><Link to="/katalog" className="text-sm font-bold text-slate-900 hover:text-[#0070F3]">Celý katalog →</Link></div><div className="grid grid-cols-[1.25fr_.9fr] gap-6 pt-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Využití podle prostoru</p><div className="mt-3 grid grid-cols-2 gap-1">{CATEGORIES.map(({ label, to, icon: Icon }) => <Link key={to} to={to} className="flex items-center gap-2 rounded-lg p-2.5 text-sm font-medium transition hover:bg-slate-50"><Icon size={16} className="shrink-0 text-[#0070F3]" />{label}</Link>)}</div></div><div className="rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan">Konstrukce a technologie</p><p className="mt-2 text-lg font-semibold">Hlavní nabídka řešení</p><div className="mt-3 space-y-1">{SOLUTIONS.map(({ label, text, to, icon: Icon }) => <Link key={to} to={to} className="group flex gap-3 rounded-lg p-3 transition hover:bg-white/10"><Icon size={19} className="mt-0.5 shrink-0 text-cyan" /><span><b className="block text-sm">{label}</b><small className="mt-1 block text-xs leading-relaxed text-white/60 group-hover:text-white/80">{text}</small></span></Link>)}</div></div></div></div>;
}