import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDown, ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const LABELS = ['Přesná výroba', 'Mikromlžení pro města', 'HolmTec know-how', 'Mlžidla ve veřejném prostoru'];

export default function AboutHero({ images }) {
  const [active, setActive] = useState(0);
  const next = () => setActive((index) => (index + 1) % images.length);
  const previous = () => setActive((index) => (index - 1 + images.length) % images.length);
  useEffect(() => { const timer = window.setInterval(next, 5500); return () => window.clearInterval(timer); }, [images.length]);
  return <section className="relative min-h-[78svh] overflow-hidden bg-slate-950 text-white"><AnimatePresence mode="wait"><motion.img key={images[active]} src={images[active]} alt={LABELS[active]} initial={{ opacity: 0, scale: 1.06 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.8 }} fetchPriority={active === 0 ? 'high' : 'auto'} decoding="async" className="absolute inset-0 h-full w-full object-cover" /></AnimatePresence><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,6,23,.9),rgba(2,6,23,.52)_53%,rgba(2,6,23,.22))]" /><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="relative mx-auto flex min-h-[78svh] max-w-7xl flex-col justify-end px-6 pb-28 pt-36 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.24em] text-cyan">O společnosti · HolmTec</p><h1 className="mt-5 max-w-4xl font-heading text-5xl font-medium leading-[.95] tracking-tight sm:text-6xl lg:text-8xl">Přesnost, která<br />osvěžuje města.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-white/78">Zkušenost z nerezové výroby přetváříme v mlžné objekty, které dávají veřejnému prostoru úlevu, charakter a život.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/poptavka" className="btn-metallic-mist min-h-12 justify-center px-7 py-4 text-sm font-bold">Navrhnout řešení <ArrowRight size={17} /></Link><a href="#pribeh" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/35 px-7 py-4 text-sm font-bold text-white transition hover:bg-white/10"><ArrowDown size={16} /> Náš příběh</a></div></motion.div><div className="absolute bottom-7 right-6 z-10 flex items-center gap-3 lg:right-10"><button type="button" onClick={previous} aria-label="Předchozí snímek" className="flex h-11 w-11 items-center justify-center rounded-full border border-white/30 bg-slate-950/30 text-white backdrop-blur transition hover:bg-white/15"><ChevronLeft size={18} /></button><div className="flex gap-2">{images.map((image, index) => <button key={image} type="button" onClick={() => setActive(index)} aria-label={`Zobrazit snímek: ${LABELS[index]}`} aria-current={active === index} className={`h-2 rounded-full transition-all ${active === index ? 'w-7 bg-cyan' : 'w-2 bg-white/45 hover:bg-white'}`} />)}</div><button type="button" onClick={next} aria-label="Další snímek" className="flex h-11 w-11 items-center justify-center rounded-full border border-white/30 bg-slate-950/30 text-white backdrop-blur transition hover:bg-white/15"><ChevronRight size={18} /></button></div><p className="absolute bottom-20 right-7 z-10 text-xs font-bold uppercase tracking-[.18em] text-white/65 lg:right-11">{LABELS[active]}</p></section>;
}