import React from 'react';
import { Factory, Layers3 } from 'lucide-react';
import { motion } from 'framer-motion';

const stories = [
  { icon: Factory, eyebrow: 'Naše kořeny', title: <>Průmyslová přesnost<br /><i className="text-slate-400">v každém detailu.</i></>, text: 'HolmTec staví na dlouhodobé zkušenosti s přesným tvarováním nerezových trubek a komponentů. Stejný cit pro materiál, odolnost a detail dnes přenášíme do projektů, které lidé zažívají venku.', imageSide: 'right' },
  { icon: Layers3, eyebrow: 'Od výroby k zážitku', title: <>Technologie, která<br /><i className="text-slate-400">patří mezi lidi.</i></>, text: 'Mlžidla.cz vznikla z potřeby ochladit přehřátá města a současně jim přidat nový důvod k zastavení. Každou realizaci navrhujeme jako technicky funkční objekt s přirozeným místem v architektuře.', imageSide: 'left' },
];

export default function AboutStory({ images }) {
  return <section id="pribeh" className="bg-white">{stories.map((story, index) => <div key={story.eyebrow} className={`border-b border-slate-200 ${index ? 'bg-slate-50' : ''}`}><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-2 lg:gap-20 lg:px-10 lg:py-32"><motion.div initial={{ opacity: 0, x: story.imageSide === 'left' ? 32 : -32 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.25 }} className={story.imageSide === 'left' ? 'lg:order-2' : ''}><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-900 text-cyan"><story.icon size={21} /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-slate-400">{story.eyebrow}</p><h2 className="mt-4 font-heading text-4xl font-medium leading-tight tracking-tight text-slate-900 lg:text-5xl">{story.title}</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">{story.text}</p></motion.div><motion.figure initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.25 }} className={story.imageSide === 'left' ? 'lg:order-1' : ''}><img src={images[index]} alt={index ? 'Archiv nerezové výroby HolmTec' : 'Detail přesného ohýbání nerezových trubek'} loading="lazy" decoding="async" className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-xl shadow-slate-900/10" /></motion.figure></div></div>)}</section>;
}