import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import Breadcrumbs from '@/components/common/Breadcrumbs';
import { partnershipData } from '@/components/partnerstvi/partnershipData';
import { setSEO } from '@/lib/seo';
import B2BReferencesSection from '@/components/reference/B2BReferencesSection';

export default function PartnerstviDetail() {
  const { type } = useParams();
  const item = partnershipData[type] || partnershipData.distributori;
  useEffect(() => setSEO({ title: `${item.title} | B2B partnerství Mlžidla.cz`, description: item.lead, canonicalPath: `/partnerstvi/${type}` }), [item, type]);
  return <main className="min-h-screen bg-white"><section className="bg-slate-950 pb-20 pt-28 text-white lg:pb-28 lg:pt-36"><div className="site-container"><Breadcrumbs light items={[{ label: 'B2B partnerství', to: '/partnerstvi' }, { label: item.eyebrow }]} /><p className="content-eyebrow mt-10 text-cyan">{item.eyebrow}</p><h1 className="mt-4 max-w-4xl text-white">{item.title}</h1><p className="mt-6 max-w-2xl text-lg text-white/75">{item.lead}</p><Link to={`/poptavka?produkt=${encodeURIComponent(item.eyebrow)}`} className="btn-metallic-mist mt-8 px-7 py-4 text-sm font-bold">Projednat spolupráci <ArrowRight size={16} /></Link></div></section><section className="site-container py-16 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="content-eyebrow">Pro koho</p><h2 className="mt-3 text-slate-950">Partnerství odpovídající vašemu oboru.</h2><p className="mt-5 text-slate-600">{item.audience}</p></div><div className="grid gap-4 sm:grid-cols-2">{item.benefits.map(benefit => <article key={benefit} className="border border-slate-200 p-6"><CheckCircle2 className="text-techblue" /><p className="mt-4 font-semibold text-slate-950">{benefit}</p></article>)}</div></div></section><section className="bg-slate-50 py-16 lg:py-20"><div className="site-container"><p className="content-eyebrow">Jak spolupráce začíná</p><h2 className="mt-3 text-slate-950">Jasný postup bez zbytečné administrativy.</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{item.process.map((step,index) => <article key={step} className="bg-white p-6"><span className="text-xs font-bold text-techblue">0{index + 1}</span><h3 className="mt-4 text-lg text-slate-950">{step}</h3></article>)}</div><div className="mt-10 border border-slate-200 bg-white p-7"><h3 className="text-xl text-slate-950">B2B cenové podmínky</h3><p className="mt-3 text-slate-600">Partnerskou cenu stanovujeme individuálně podle typu spolupráce, objemu, opakovanosti objednávek a rozsahu technické podpory. Před zahájením spolupráce obdržíte přehlednou nabídku bez skrytých poplatků.</p></div></div></section><B2BReferencesSection context={type === 'verejny-sektor' ? 'mesta-obce' : 'architekti'} title="Důkaz partnerství v reálných projektech." /></main>;
}