import React, { useEffect, useState } from 'react';
import { ArrowRight, Loader, Mail, MapPin, Phone } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { trackContactFormSubmit, trackInquirySubmitted } from '@/lib/ga4';
import { setSEO } from '@/lib/seo';
import InquiryHero from '@/components/premium/InquiryHero';
import InquiryTrust from '@/components/premium/InquiryTrust';

const products = ['City Collection', 'Garden Collection', 'Zakázkové řešení', 'Smart řízení', 'Ještě nevím'];
const input = 'w-full border-b border-slate-300 bg-transparent px-0 py-3 text-sm text-slate-950 placeholder:text-slate-400 focus:border-teal-700 focus:outline-none';

export default function Poptavka() {
  const navigate = useNavigate();
  const [sending, setSending] = useState(false);
  const [form, setForm] = useState({ jmeno: '', email: '', telefon: '', firma: '', produkt: '', zprava: '' });
  useEffect(() => setSEO({ title: 'Nezávazná poptávka | MLŽIDLA®', description: 'Navrhneme architektonický mlžicí systém přesně pro váš prostor.', canonicalPath: '/poptavka' }), []);
  const change = (name) => (event) => setForm((values) => ({ ...values, [name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSending(true); try { await base44.entities.Poptavka.create({ ...form, status: 'nova' }); trackContactFormSubmit('poptavka', form.produkt); trackInquirySubmitted('poptavka', form.produkt); navigate('/dekujeme?zdroj=poptavka'); } finally { setSending(false); } };
  return <div className="bg-[#fcfcfa]"><InquiryHero/><section className="max-w-7xl mx-auto px-6 lg:px-8 py-14 lg:py-20"><div className="grid lg:grid-cols-[.72fr_1.28fr] gap-12 lg:gap-20"><aside><p className="font-mono text-[11px] tracking-[0.18em] uppercase text-teal-700 mb-4">Konzultace</p><h2 className="font-heading text-4xl text-slate-950">Řekněte nám, co potřebujete.</h2><p className="mt-5 text-slate-600 leading-relaxed">Stačí několik informací. Pomůžeme vám vybrat vhodnou kolekci, rozsah systému i způsob ovládání.</p><div className="mt-10 space-y-5 text-sm text-slate-700"><a href="tel:+420774700390" className="flex gap-3 items-center"><Phone size={17} className="text-teal-700"/>+420 774 700 390</a><a href="mailto:obchod1@holmtec.cz" className="flex gap-3 items-center"><Mail size={17} className="text-teal-700"/>obchod1@holmtec.cz</a><p className="flex gap-3 items-start"><MapPin size={17} className="mt-0.5 text-teal-700"/>Trutnov, Česká republika</p></div></aside><div><InquiryTrust/><form onSubmit={submit} className="border border-slate-200 bg-white p-6 lg:p-10"><div className="grid sm:grid-cols-2 gap-x-7 gap-y-6"><label className="text-xs font-mono tracking-wider uppercase text-slate-500">Jméno a příjmení *<input required value={form.jmeno} onChange={change('jmeno')} placeholder="Jan Novák" className={input}/></label><label className="text-xs font-mono tracking-wider uppercase text-slate-500">E-mail *<input required type="email" value={form.email} onChange={change('email')} placeholder="jan@firma.cz" className={input}/></label><label className="text-xs font-mono tracking-wider uppercase text-slate-500">Telefon<input value={form.telefon} onChange={change('telefon')} placeholder="+420 000 000 000" className={input}/></label><label className="text-xs font-mono tracking-wider uppercase text-slate-500">Firma / organizace<input value={form.firma} onChange={change('firma')} placeholder="Název organizace" className={input}/></label></div><label className="block mt-7 text-xs font-mono tracking-wider uppercase text-slate-500">Typ projektu<select value={form.produkt} onChange={change('produkt')} className={input}>{products.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block mt-7 text-xs font-mono tracking-wider uppercase text-slate-500">Jaký prostor řešíte? *<textarea required value={form.zprava} onChange={change('zprava')} rows={4} placeholder="Místo instalace, rozměry, počet návštěvníků nebo váš záměr…" className={`${input} resize-none`}/></label><button disabled={sending} className="btn-inquiry-pulse mt-9 inline-flex items-center gap-2 rounded-full bg-primary px-7 py-4 text-sm font-bold text-primary-foreground disabled:opacity-60">{sending ? <Loader size={17} className="animate-spin"/> : <>Odeslat poptávku <ArrowRight size={16}/></>}</button><p className="mt-5 text-xs text-slate-400">Odesláním souhlasíte se zpracováním osobních údajů.</p></form></div></div></section></div>;
}