import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Check, ChevronLeft } from 'lucide-react';
import { BENEFITS } from '@/lib/benefitsContent';
import { setSEO } from '@/lib/seo';

export default function PrinosMlzitek() {
  const { slug } = useParams();
  const page = BENEFITS[slug] || BENEFITS['zvyseni-trzeb-a-prodeje'];
  useEffect(() => setSEO({ title: `${page.title} | Mlžidla.cz`, description: page.subtitle, canonicalPath: `/prinosy-mlzitek/${slug}` }), [page, slug]);
  return <main className="bg-white pt-16"><section className="bg-slate-950 text-white py-20 lg:py-28"><div className="max-w-5xl mx-auto px-6 lg:px-8"><Link to="/vyhody" className="inline-flex items-center gap-2 text-xs text-white/60 hover:text-white mb-8"><ChevronLeft size={14} /> Přínosy mlžítek</Link><p className="text-xs uppercase tracking-[0.22em] text-cyan mb-4">{page.eyebrow}</p><h1 className="font-heading font-light text-white text-4xl lg:text-6xl max-w-4xl">{page.title}</h1><p className="text-white/75 text-xl max-w-3xl mt-6">{page.subtitle}</p></div></section><section className="max-w-5xl mx-auto px-6 lg:px-8 py-16 lg:py-24 grid lg:grid-cols-[1fr_0.8fr] gap-12"><div><p className="text-slate-600 text-lg leading-relaxed">{page.lead}</p><div className="mt-9 space-y-4">{page.points.map((point) => <div key={point} className="flex gap-3 text-slate-800"><span className="mt-1 w-5 h-5 rounded-full bg-slate-900 text-white flex items-center justify-center shrink-0"><Check size={12} /></span><p>{point}</p></div>)}</div></div><aside className="rounded-3xl bg-slate-100 p-8"><p className="text-xs uppercase tracking-widest text-slate-400">Klíčový argument</p><p className="font-heading text-3xl text-slate-900 mt-4">{page.metric}</p><p className="text-sm text-slate-500 mt-3">Výkon, který dává smysl pro provoz i rozpočet.</p></aside></section><section className="bg-slate-50 py-16 lg:py-20"><div className="max-w-5xl mx-auto px-6 lg:px-8"><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Z praxe</p><h2 className="font-heading text-slate-900 text-3xl mt-3">{page.caseTitle}</h2><p className="text-slate-600 max-w-3xl mt-5 leading-relaxed">{page.caseText}</p></div></section><section className="max-w-5xl mx-auto px-6 lg:px-8 py-16 lg:py-24"><h2 className="font-heading text-3xl text-slate-900">Pojďme spočítat přínos pro váš prostor.</h2><p className="text-slate-500 mt-4 max-w-xl">Navrhneme řešení podle cíle, provozu a technických možností vašeho místa.</p><Link to="/poptavka" className="btn-metallic-mist px-7 py-3.5 text-sm font-bold mt-7">Nezávazná poptávka <ArrowRight size={16} /></Link><div className="border-t border-slate-200 mt-16 pt-8"><p className="text-xs uppercase tracking-widest text-slate-400 mb-4">Další přínosy</p><div className="flex flex-wrap gap-2">{Object.entries(BENEFITS).filter(([key]) => key !== slug).map(([key, item]) => <Link key={key} to={`/prinosy-mlzitek/${key}`} className="px-4 py-2 rounded-full border border-slate-200 text-sm text-slate-700 hover:border-slate-900 hover:text-slate-900 transition-colors">{item.eyebrow.split(' · ')[0]}</Link>)}</div></div></section></main>;
}