import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Check, ChevronLeft } from 'lucide-react';
import { BENEFITS } from '@/lib/benefitsContent';
import { BENEFIT_METRIC_NOTES, BENEFIT_NAVIGATION } from '@/lib/benefitNavigation';
import { setSEO } from '@/lib/seo';
import MistHeroBackground from '@/components/common/MistHeroBackground';

export default function PrinosMlzitek() {
  const { slug } = useParams();
  const page = BENEFITS[slug] || BENEFITS['zvyseni-trzeb-a-prodeje'];
  useEffect(() => setSEO({ title: `${page.title} | Mlžidla.cz`, description: page.subtitle, canonicalPath: `/prinosy-mlzitek/${slug}` }), [page, slug]);
  return <main className="bg-white"><section className="relative overflow-hidden bg-slate-950 text-white pt-28 pb-20 lg:pt-36 lg:pb-28"><MistHeroBackground /><div className="relative z-10 max-w-5xl mx-auto px-6 lg:px-8"><Link to="/prinosy-mlzitek" className="inline-flex items-center gap-2 text-xs text-white/60 hover:text-white mb-8"><ChevronLeft size={14} /> Přínosy mlžítek</Link><p className="text-xs uppercase tracking-[0.22em] text-cyan mb-4">{page.eyebrow}</p><h1 className="font-heading font-light text-white text-4xl lg:text-6xl max-w-4xl">{page.title}</h1><p className="text-white/75 text-xl max-w-3xl mt-6">{page.subtitle}</p></div></section><section className="max-w-5xl mx-auto px-6 lg:px-8 py-16 lg:py-24 grid lg:grid-cols-[1fr_0.8fr] gap-12"><div><p className="text-slate-600 text-lg leading-relaxed">{page.lead}</p><div className="mt-9 space-y-4">{page.points.map((point) => <div key={point} className="flex gap-3 text-slate-800"><span className="mt-1 w-5 h-5 rounded-full bg-slate-900 text-white flex items-center justify-center shrink-0"><Check size={12} /></span><p>{point}</p></div>)}</div></div><aside className="rounded-3xl bg-slate-100 p-8"><p className="text-xs uppercase tracking-widest text-slate-400">Klíčový přínos</p><p className="font-heading text-3xl text-slate-900 mt-4">{page.metric}</p><p className="text-sm text-slate-600 mt-3 leading-relaxed">{BENEFIT_METRIC_NOTES[slug] || BENEFIT_METRIC_NOTES['zvyseni-trzeb-a-prodeje']}</p></aside></section><section className="bg-slate-50 py-16 lg:py-20"><div className="max-w-5xl mx-auto px-6 lg:px-8"><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Z praxe</p><h2 className="font-heading text-slate-900 text-3xl mt-3">{page.caseTitle}</h2><p className="text-slate-600 max-w-3xl mt-5 leading-relaxed">{page.caseText}</p></div></section><section className="max-w-5xl mx-auto px-6 lg:px-8 py-16 lg:py-24"><h2 className="font-heading text-3xl text-slate-900">Pojďme spočítat přínos pro váš prostor.</h2><p className="text-slate-500 mt-4 max-w-xl">Navrhneme řešení podle cíle, provozu a technických možností vašeho místa.</p><Link to="/poptavka" className="btn-metallic-mist px-7 py-3.5 text-sm font-bold mt-7">Nezávazná poptávka <ArrowRight size={16} /></Link><div className="border-t border-slate-200 mt-16 pt-8"><p className="text-xs uppercase tracking-widest text-slate-400 mb-4">Další přínosy</p><div className="grid gap-3 sm:grid-cols-3">{Object.entries(BENEFITS).filter(([key]) => key !== slug).map(([key]) => <Link key={key} to={`/prinosy-mlzitek/${key}`} className="group flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-semibold text-slate-800 transition-all hover:-translate-y-0.5 hover:border-slate-900 hover:shadow-lg"><span>{BENEFIT_NAVIGATION[key]}</span><ArrowRight size={16} className="shrink-0 text-slate-400 transition-transform group-hover:translate-x-1 group-hover:text-slate-900" /></Link>)}</div></div></section></main>;
}