import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, ShieldCheck, Smartphone, WalletCards } from 'lucide-react';
import { setSEO } from '@/lib/seo';

const items = [
  { title: 'Zvýšení tržeb a prodeje', text: 'Plnější terasa, delší pobyt hostů a silnější viditelnost z ulice.', path: '/prinosy-mlzitek/zvyseni-trzeb-a-prodeje', icon: BarChart3 },
  { title: 'Automatizace provozu', text: 'SMART APP a meteočidla řídí mlžení bez další práce personálu.', path: '/prinosy-mlzitek/automatizace-provozu', icon: Smartphone },
  { title: 'Zabezpečení a shoda', text: 'Filtrace, hygiena vody a jasný dohled pro veřejný prostor.', path: '/prinosy-mlzitek/zabezpeceni-a-shoda', icon: ShieldCheck },
  { title: 'Snižování nákladů', text: 'Přesně řízená spotřeba a nerezová konstrukce na dlouhé roky.', path: '/prinosy-mlzitek/snizovani-provoznich-nakladu', icon: WalletCards },
];
export default function Prinosy() { useEffect(() => { setSEO({ title: 'Přínosy mlžítek | Mlžidla.cz', description: 'Ekonomické, provozní a ekologické přínosy mlžných systémů HolmTec.', canonicalPath: '/prinosy-mlzitek' }); }, []); return <main className="min-h-screen bg-white pt-16"><section className="bg-slate-950 text-white py-20 lg:py-28"><div className="max-w-7xl mx-auto px-6 lg:px-10"><p className="text-xs uppercase tracking-[.22em] text-cyan mb-4">Přínosy pro B2B</p><h1 className="font-heading font-light text-4xl lg:text-6xl max-w-4xl">Mlha, která pracuje pro váš provoz.</h1><p className="mt-6 max-w-2xl text-white/65 text-lg">Od vyšších tržeb až po chytrou automatizaci. Vyberte si přínos, který je pro váš projekt nejdůležitější.</p></div></section><section className="max-w-7xl mx-auto px-6 lg:px-10 py-14 lg:py-20"><div className="grid md:grid-cols-2 gap-4">{items.map((item) => <Link key={item.path} to={item.path} className="group border border-slate-200 p-7 flex gap-5 hover:bg-slate-950 hover:border-slate-950 transition-colors"><item.icon size={25} className="text-sky-500 shrink-0"/><div><h2 className="font-heading text-xl font-medium text-slate-950 group-hover:text-white">{item.title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-500 group-hover:text-white/60">{item.text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-950 group-hover:text-cyan">Zjistit více <ArrowRight size={15}/></span></div></Link>)}</div></section></main>; }