import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight, Droplets, Factory, Gauge, Layers, Loader, Ruler, Sparkles, Truck, Waves, X, Zap } from 'lucide-react';
import gsap from 'gsap';
import { ScrollToPlugin } from 'gsap/ScrollToPlugin';
import { base44 } from '@/api/base44Client';
import { trackProductView } from '@/lib/ga4';
import { getProductSEO, setSEO } from '@/lib/seo';
import ProductHero from '@/components/produkt/ProductHero';
import ProductDetailContent from '@/components/produkt/ProductDetailContent';
import ProductStickyFooterBar from '@/components/produkt/ProductStickyFooterBar';
import ProductContactForm from '@/components/produkt/ProductContactForm';
import ProductReviews from '@/components/reviews/ProductReviews';
import MistFogEffect from '@/components/produkt/MistFogEffect';

gsap.registerPlugin(ScrollToPlugin);
const ACCESSORY_CATEGORY_ID = '6a5119a4abdfd991c476d9fc';

function Lightbox({ images, initialIndex, onClose }) {
  const [index, setIndex] = useState(initialIndex);
  useEffect(() => { const keyHandler = (event) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowRight') setIndex((i) => (i + 1) % images.length); if (event.key === 'ArrowLeft') setIndex((i) => (i - 1 + images.length) % images.length); }; window.addEventListener('keydown', keyHandler); return () => window.removeEventListener('keydown', keyHandler); }, [images.length, onClose]);
  return <div className="fixed inset-0 z-[200] bg-black/95 backdrop-blur-xl flex items-center justify-center" onClick={onClose}><button onClick={onClose} aria-label="Zavřít galerii" className="absolute top-5 right-5 w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-white"><X size={18} /></button><div className="relative max-w-5xl w-full mx-6" onClick={(event) => event.stopPropagation()}><img src={images[index]} alt={`Fotografie ${index + 1}`} className="w-full max-h-[85vh] object-contain" />{images.length > 1 && <><button onClick={() => setIndex((i) => (i - 1 + images.length) % images.length)} className="absolute left-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/60 text-white flex items-center justify-center"><ChevronLeft size={18} /></button><button onClick={() => setIndex((i) => (i + 1) % images.length)} className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/60 text-white flex items-center justify-center"><ChevronRight size={18} /></button></>}</div></div>;
}

export default function ProduktDetail() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const contactRef = useRef(null);
  const [product, setProduct] = useState(null); const [categories, setCategories] = useState([]); const [related, setRelated] = useState([]); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [lightbox, setLightbox] = useState(null); const [showStickyBar, setShowStickyBar] = useState(false);
  useEffect(() => { base44.entities.ProductCategory.list().then(setCategories); }, []);
  useEffect(() => { if (slug === 'gate70') { navigate('/gate70', { replace: true }); return; } setLoading(true); base44.entities.Product.filter({ slug }).then(async (items) => { if (!items?.length) { setNotFound(true); return; } const found = items[0]; setProduct(found); trackProductView(found.name, found.slug, found.category_id); setSEO(getProductSEO(found)); const products = await base44.entities.Product.filter({ category_id: found.category_id }); setRelated(products.filter((item) => item.id !== found.id).slice(0, 3)); }).catch(() => setNotFound(true)).finally(() => setLoading(false)); }, [slug]);
  useEffect(() => { const onScroll = () => setShowStickyBar(window.scrollY > 520); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  const scrollToContact = () => gsap.to(window, { duration: 0.85, scrollTo: { y: contactRef.current, offsetY: 80 }, ease: 'power2.inOut' });
  if (loading) return <div className="min-h-screen bg-white flex items-center justify-center"><Loader size={28} className="animate-spin text-slate-300" /></div>;
  if (notFound || !product) return <div className="min-h-screen bg-white flex items-center justify-center"><div className="text-center"><p className="text-slate-400 mb-4 text-lg">Produkt nenalezen.</p><Link to="/mlzidla-mlzitka" className="text-slate-900 hover:underline">← Zpět na mlžítka</Link></div></div>;
  const isAccessory = product.category_id === ACCESSORY_CATEGORY_ID; const allImages = [product.image_url, ...(product.gallery_urls || [])].filter(Boolean); const categoryName = categories.find((category) => category.id === product.category_id)?.name || '';
  const techRows = [product.coverage_area && { label: 'Výška', value: product.coverage_area, icon: Ruler, desc: 'Celková výška konstrukce ovlivňuje dosah mlžného oblaku.' }, { label: 'Trysky', value: product.micron_size ? `AISI 316L, ${product.micron_size} μm` : 'AISI 316L', icon: Waves, desc: 'Nerezové trysky rozprašují vodu na mikrokapky, které se okamžitě odpaří.' }, product.pressure && { label: 'Tlak', value: product.pressure, icon: Gauge, desc: 'Nízkotlaký provoz umožňuje přímé napojení na běžný vodovodní řad.' }, product.water_consumption && { label: 'Spotřeba vody', value: product.water_consumption, icon: Droplets, desc: 'Reálná spotřeba při plynulém provozu.' }, product.material && { label: 'Materiál', value: product.material, icon: Layers, desc: 'Odolný materiál vhodný pro celoroční venkovní provoz.' }, { label: 'Povrch', value: 'Broušený / kartáčovaný', icon: Sparkles, desc: 'Prémiový povrch potlačuje odlesky a otisky prstů.' }, product.power_supply && { label: 'Napájení a řízení', value: product.power_supply, icon: Zap, desc: 'Kompatibilní se SMART moduly a časovači.' }, !isAccessory && { label: 'Výroba', value: 'Zakázková, 6–8 týdnů', icon: Factory, desc: 'Každý kus se vyrábí na zakázku v ČR.' }, isAccessory && { label: 'Dodání', value: 'Do 7 prac. dnů', icon: Truck, desc: 'Pro přesný termín kontaktujte podporu.' }].filter(Boolean);
  return <div className="min-h-screen bg-white"><ProductHero product={product} categoryName={categoryName} allImages={allImages} onOpenLightbox={(index) => setLightbox({ images: allImages, index })} isAccessory={isAccessory} /><ProductDetailContent product={product} techRows={techRows} allImages={allImages} isAccessory={isAccessory} onOpenLightbox={(index) => setLightbox({ images: allImages, index })} /><ProductReviews productId={product.id} onStatsLoaded={(stats) => setSEO(getProductSEO(product, stats))} /><section ref={contactRef} className="bg-gradient-to-b from-slate-900 to-slate-800 py-24 relative overflow-hidden"><MistFogEffect /><div className="max-w-6xl mx-auto px-6 lg:px-10 relative grid lg:grid-cols-[0.85fr_1.15fr] gap-12 lg:gap-16"><div><span className="inline-block px-4 py-1.5 bg-white/10 border border-white/20 text-white text-xs font-bold tracking-widest uppercase rounded-full mb-5">Nezávazná poptávka</span><h2 className="font-heading font-semibold text-white text-3xl lg:text-4xl">Vyžádejte si cenu<br /><span className="font-light text-sky-300">pro váš projekt.</span></h2><p className="text-white/70 text-base leading-relaxed text-measure">Konzultace zdarma, 3D vizualizace do 48 hodin a odpověď do jednoho pracovního dne.</p></div><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><ProductContactForm productName={product.name} /></motion.div></div></section>{related.length > 0 && <section className="py-20 bg-white border-t border-slate-200"><div className="max-w-7xl mx-auto px-6 lg:px-10"><p className="text-xs font-mono tracking-widest uppercase text-slate-400 mb-3">Mohlo by vás zajímat</p><h2 className="font-heading font-bold text-3xl text-slate-900">Podobné produkty</h2><div className="grid md:grid-cols-3 gap-5 mt-8">{related.map((item) => <Link key={item.id} to={`/produkt/${item.slug}`} className="group rounded-2xl overflow-hidden border border-slate-200"><div className="aspect-[4/3] bg-slate-100">{item.image_url && <img src={item.image_url} alt={item.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />}</div><div className="p-5 flex items-center justify-between"><span className="font-semibold text-slate-900">{item.name}</span><ArrowRight size={16} className="text-slate-400" /></div></Link>)}</div><Link to="/mlzidla-mlzitka" className="inline-flex items-center gap-2 text-sm text-slate-500 mt-10"><ArrowLeft size={14} /> Zpět na celou kolekci</Link></div></section>}{lightbox && <Lightbox images={lightbox.images} initialIndex={lightbox.index} onClose={() => setLightbox(null)} />}<ProductStickyFooterBar product={product} show={showStickyBar} onPoptat={scrollToContact} /></div>;
}