import React, { useEffect, useState } from 'react';
import { CalendarDays, PartyPopper, ShieldCheck } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { setSEO } from '@/lib/seo';
import RentalProductGrid from '@/components/pronajem/RentalProductGrid';
import RentalInquiryForm from '@/components/pronajem/RentalInquiryForm';

const FEATURES = [{ Icon: PartyPopper, text: 'Eventy, festivaly a letní večírky' }, { Icon: CalendarDays, text: 'Krátkodobý i vícedenní pronájem' }, { Icon: ShieldCheck, text: 'Doprava, instalace a technická podpora' }];
export default function Pronajem() {
  const [products, setProducts] = useState([]);
  useEffect(() => { setSEO({ title: 'Pronájem mlžítek GO | MLŽIDLA®', description: 'Mobilní mlžítka a mlžné brány pro eventy, festivaly a letní akce.', canonicalPath: '/pronajem' }); base44.entities.Product.list().then(setProducts); }, []);
  return <main className="bg-background pt-16"><section className="relative overflow-hidden bg-primary py-20 text-primary-foreground lg:py-28"><div className="absolute inset-0 opacity-25"><img src="https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/b68df5d31_Gemini_Generated_Image_5gclad5gclad5gcl.png" alt="Pronájem mlžné brány na akci" className="h-full w-full object-cover"/></div><div className="relative mx-auto max-w-7xl px-6 lg:px-10"><p className="font-mono text-[11px] tracking-[.18em] text-accent">KOLEKCE GO · PRONÁJEM</p><h1 className="mt-5 max-w-4xl font-heading text-5xl lg:text-7xl">Ochlazení, které přijede přímo na vaši akci.</h1><p className="mt-6 max-w-2xl text-lg text-primary-foreground/75">Mobilní mlžítka pro festivaly, firemní večírky, Den dětí, svatby a všechny letní události.</p><div className="mt-10 grid max-w-4xl gap-4 sm:grid-cols-3">{FEATURES.map(({ Icon, text }) => <div key={text} className="flex gap-3 border-t border-white/20 pt-4 text-sm"><Icon size={18} className="shrink-0 text-accent"/>{text}</div>)}</div></div></section><section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><p className="font-mono text-[11px] tracking-[.18em] text-secondary">VŠECHNY MODELY VE VERZI GO</p><h2 className="mb-10 mt-3 font-heading text-4xl text-foreground">Vyberte mlžítko pro svou událost.</h2><RentalProductGrid products={products}/></section><section className="bg-muted/40 py-20"><div className="mx-auto grid max-w-6xl gap-10 px-6 lg:grid-cols-[.75fr_1.25fr] lg:px-10"><div><p className="font-mono text-[11px] tracking-[.18em] text-secondary">EVENTOVÁ POPTÁVKA</p><h2 className="mt-3 font-heading text-4xl text-foreground">Poptat cenu pronájmu.</h2><p className="mt-4 text-muted-foreground">Pošlete nám termín a typ akce. Doporučíme model, počet zařízení i vhodné rozmístění.</p></div><RentalInquiryForm products={products}/></div></section></main>;
}