import React, { useEffect } from 'react';
import { ArrowRight, Building2, Trees, Hotel, Utensils } from 'lucide-react';
import { Link } from 'react-router-dom';
import { setSEO } from '@/lib/seo';
import ReferenceMetrics from '@/components/premium/ReferenceMetrics';
import ReferenceShowcase from '@/components/premium/ReferenceShowcase';

const sectors = [[Building2, 'Města'], [Trees, 'Parky'], [Hotel, 'Hotely'], [Utensils, 'Restaurace']];

export default function Reference() {
  useEffect(() => setSEO({ title: 'Realizace mlžítek a mlžných bran | MLŽIDLA®', description: 'Realizace nerezových mlžítek a mlžných bran pro města, parky, zahrady, hotely a restaurace.', canonicalPath: '/reference' }), []);
  return <div className="bg-background pt-16"><section className="relative min-h-[620px] overflow-hidden bg-primary"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_85%_42%,#2BBFCF_0%,#1A85B0_34%,#0A1628_72%)]"/><div className="absolute inset-0 bg-gradient-to-r from-primary via-primary/70 to-transparent"/><div className="relative max-w-7xl mx-auto px-6 lg:px-8 pt-32 pb-20"><p className="font-mono text-[11px] tracking-[0.18em] uppercase text-cyan mb-5">Vybrané realizace</p><h1 className="font-heading text-5xl lg:text-7xl leading-[.98] max-w-3xl text-white">Realizace mlžítek a mlžných bran pro příjemnější prostor.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/75">Navrhujeme nerezové mlžicí systémy pro místa, kde lidé zůstávají déle, cítí se lépe a rádi se vracejí.</p><Link to="/poptavka" className="mt-9 inline-flex items-center gap-2 bg-white px-6 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-50">Navrhnout váš prostor <ArrowRight size={16}/></Link></div></section><ReferenceMetrics/><section className="max-w-7xl mx-auto px-6 lg:px-8 py-10 grid grid-cols-2 lg:grid-cols-4 border-b border-slate-200">{sectors.map(([Icon, label]) => <Link to="/poptavka" key={label} className="group flex items-center justify-center gap-3 py-5 border-r border-slate-200 last:border-0"><Icon size={19} className="text-teal-700 group-hover:scale-110 transition-transform"/><span className="font-medium text-slate-700">{label}</span></Link>)}</section><ReferenceShowcase/><section className="bg-[#062d3b] py-20"><div className="max-w-7xl mx-auto px-6 lg:px-8 grid lg:grid-cols-[1fr_auto] gap-8 items-end"><div><p className="font-mono text-[11px] tracking-[0.18em] uppercase text-cyan mb-4">Váš projekt</p><h2 className="font-heading text-4xl lg:text-6xl text-white max-w-3xl">Navrhneme řešení přesně pro váš prostor.</h2></div><div className="flex flex-wrap gap-3"><Link to="/poptavka" className="bg-cyan px-6 py-3 text-sm font-bold text-slate-950">Popsat projekt</Link><Link to="/kontakt" className="border border-white/35 px-6 py-3 text-sm font-semibold text-white">Probrat záměr</Link></div></div></section></div>;
}