import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, ChevronRight, Cpu, MapPin, ShieldCheck, ThermometerSnowflake } from 'lucide-react';
import { setSEO } from '@/lib/seo';
import CategoryInquiryForm from '@/components/kategorie/CategoryInquiryForm';
import UsageRecommendedProducts from '@/components/vyuziti/UsageRecommendedProducts';
import { usageCategories } from '@/components/vyuziti/usageCategoryData';

const icons = [ThermometerSnowflake, ShieldCheck, Cpu];

export default function UsageCategory() {
  const { sector } = useParams();
  const item = usageCategories[sector] || usageCategories['mesta-obce'];
  useEffect(() => setSEO({ title: `${item.title} | Mlžidla.cz`, description: item.lead, canonicalPath: `/vyuziti/${sector}` }), [item, sector]);
  return <main className="min-h-screen bg-white"><section className="relative h-[80vh] min-h-[560px] overflow-hidden bg-slate-950 text-white"><video src={item.video} poster={item.image} autoPlay loop muted playsInline className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/55 to-slate-950/35" /><div className="site-container relative flex h-full items-end pb-16"><div className="max-w-3xl"><nav className="mb-6 flex items-center gap-2 text-xs text-white/65"><Link to="/vyuziti">B2B využití</Link><ChevronRight size={13} /><span>{item.title}</span></nav><p className="content-eyebrow text-cyan">Řešení podle prostoru</p><h1 className="mt-4 text-white">{item.title}</h1><p className="mt-6 max-w-2xl text-lg text-white/80">{item.lead}</p><a href="#poptavka" className="btn-metallic-mist mt-8 px-7 py-3.5 text-sm font-bold">Navrhnout řešení <ArrowRight size={15} /></a></div></div></section><section className="border-y border-slate-200 bg-slate-50 py-16"><div className="site-container grid gap-10 lg:grid-cols-2"><div><p className="content-eyebrow">Přínosy pro provoz</p><h2 className="mt-3 text-slate-950">Co mlžítko tomuto místu přinese.</h2><div className="mt-8 grid gap-7 sm:grid-cols-3">{item.benefits.map((benefit,index) => { const Icon=icons[index]; return <article key={benefit}><Icon className="text-techblue" size={48} strokeWidth={1.4} /><p className="mt-4 text-lg font-semibold text-slate-950">{benefit}</p></article>; })}</div></div><div className="grid grid-cols-2 gap-4">{item.places.map(place => <div key={place} className="border border-slate-200 bg-white p-6"><MapPin className="text-techblue" size={20} /><p className="mt-5 font-semibold text-slate-950">{place}</p></div>)}</div></div></section><section className="relative overflow-hidden bg-slate-950 py-20 text-white"><div className="site-container"><p className="content-eyebrow text-cyan">Smart řízení</p><h2 className="mt-3 max-w-2xl text-white">Provoz pouze tehdy, kdy dává smysl.</h2><p className="mt-5 max-w-xl text-white/70">Teplotní, časové a pohybové spouštění omezuje zbytečnou spotřebu vody a přizpůsobí mlžení skutečnému využití prostoru.</p><Link to="/chytra-mlzidla" className="mt-6 inline-flex font-bold text-cyan">Prozkoumat chytré řízení →</Link></div></section><UsageRecommendedProducts /><section id="poptavka" className="site-container grid gap-10 py-20 lg:grid-cols-[.8fr_1.2fr]"><div><p className="content-eyebrow">Nezávazná konzultace</p><h2 className="mt-3 text-slate-950">Připravíme nabídku pro konkrétní místo.</h2><p className="mt-4 text-slate-600">Zohledníme pohyb lidí, zdroj vody, kotvení, počet trysek i vhodný model mlžítka.</p><Link to="/reference" className="mt-6 inline-block font-bold text-techblue">Ukázky realizací →</Link></div><CategoryInquiryForm category={item.title} projectScope={item.scope} /></section></main>;
}