import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { HeartPulse, Hotel, ThermometerSnowflake, Waves } from 'lucide-react';
import { setSEO } from '@/lib/seo';
import UsageRecommendedProducts from '@/components/vyuziti/UsageRecommendedProducts';
import CategoryInquiryForm from '@/components/kategorie/CategoryInquiryForm';

const sectors = {
  'domovy-senioru': { icon: HeartPulse, title: 'Mlžící systémy pro domovy seniorů a domovy s pečovatelskou službou', meta: 'Ochrana seniorů před vlnami veder. Profesionální mlžítka a mlžící brány pro bezpečný a komfortní pobyt na zahradách domovů důchodců.', lead: 'Úleva od úmorného horka pro bezpečný a důstojný pobyt na zahradě.', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/97fea19c4_generated_image.png', benefits: ['Prevence dehydratace a snížení tepelného stresu', 'Podpora přirozené termoregulace bez šoku z klimatizace', 'Více komfortního času v zahradě a altánech'], technical: 'Automatické spínání podle teploty, nízká hlučnost a řízená hygiena vody pro pravidelný bezpečný provoz.' },
  hotely: { icon: Hotel, title: 'Profesionální mlžení pro hotelové areály, atria a restaurace', meta: 'Zvyšte komfort svých hostů a prodlužte jejich pobyt na hotelových terasách. Designová mlžítka a mlžící systémy na míru pro prémiové hotely.', lead: 'Konkurenční výhoda, která přirozeně láká hosty na venkovní terasu.', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/3a74be287_generated_image.png', benefits: ['Delší pobyt hostů během horkých dnů', 'Vyšší atraktivita venkovního posezení', 'Exkluzivní vizuální efekt pro hotelový areál'], technical: 'Nerezové a designové prvky s diskrétním nízkotlakým mlžením pro čisté stolování a komfort hostů.' },
  'wellness-terasy': { icon: Waves, title: 'Mlžící systémy pro wellness zóny, saunové světy a relaxační terasy', meta: 'Dokonalé ochlazení po sauně a osvěžení během letního relaxu. Mlžná oáza pro vaše wellness centrum, spa a venkovní odpočívárny.', lead: 'Prohloubení zážitku z odpočinku v jemné mlžné oáze.', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/df7fd8000_generated_image.png', benefits: ['Příjemné ochlazení po sauně', 'Osvěžení venkovních relaxačních zón', 'Prémiový zážitek pro náročné klienty'], technical: 'Jemné nízkotlaké mlžení 2–8 bar (200–800 kPa) vytváří komfortní přechodovou zónu pro odpočinek.' },
};

export default function UsageSector() {
  const { sector } = useParams();
  const item = sectors[sector] || sectors.hotely;
  const Icon = item.icon;
  useEffect(() => { setSEO({ title: `${item.title} | Mlžidla.cz`, description: item.meta, canonicalPath: `/vyuziti/${sector}` }); }, [item, sector]);
  return <main className="min-h-screen bg-white"><section className="relative isolate min-h-[560px] overflow-hidden bg-slate-950 text-white"><img src={item.image} alt={item.title} className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-slate-950/70" /><div className="site-container flex min-h-[560px] items-end py-20"><div className="max-w-3xl"><Icon className="text-[#0070F3]" size={30} /><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">B2B řešení</p><h1 className="mt-4">{item.title}</h1><p className="mt-6 text-lg leading-relaxed text-white/75">{item.lead}</p></div></div></section><section className="site-container grid gap-10 py-16 lg:grid-cols-2 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Přínosy</p><h2 className="mt-3 text-slate-950">Komfort pro návštěvníky. Jistota pro provoz.</h2><ul className="mt-7 space-y-4 pl-0">{item.benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-slate-700"><ThermometerSnowflake className="shrink-0 text-[#0070F3]" size={19} />{benefit}</li>)}</ul></div><div className="border-l-4 border-[#0070F3] bg-slate-50 p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">Technické řešení</p><p className="mt-4 text-lg leading-relaxed text-slate-800">{item.technical}</p></div></section><UsageRecommendedProducts /><section className="site-container grid gap-10 py-16 lg:grid-cols-[.8fr_1.2fr] lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Nezávazná konzultace</p><h2 className="mt-3 text-slate-950">Připravíme návrh na míru.</h2><p className="mt-4 text-slate-600">Popište nám svůj prostor a požadovaný provoz. Ozveme se do 24 hodin.</p><Link to="/reference" className="mt-6 inline-block text-sm font-bold text-[#0070F3]">Ukázky realizací →</Link></div><CategoryInquiryForm category={item.title} projectScope="private" /></section></main>;
}