import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CheckCircle, MapPin } from 'lucide-react';
import { setSEO } from '@/lib/seo';
import CategoryInquiryForm from '@/components/kategorie/CategoryInquiryForm';
import UsageRecommendedProducts from '@/components/vyuziti/UsageRecommendedProducts';
import { usageCategories } from '@/components/vyuziti/usageCategoryData';

export default function UsageCategory() {
  const { sector } = useParams();
  const item = usageCategories[sector] || usageCategories['mesta-obce'];
  const [image] = useState(() => item.image);
  useEffect(() => setSEO({ title: `${item.title} | Mlžidla.cz`, description: item.lead, canonicalPath: `/vyuziti/${sector}` }), [item, sector]);
  return <main className="min-h-screen bg-white"><section className="relative h-[80vh] min-h-[560px] overflow-hidden bg-slate-950 text-white"><img src={image} alt={item.title} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/45 to-slate-950/40" /><div className="site-container relative flex h-full items-end pb-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Využití podle prostoru</p><h1 className="mt-4 font-heading font-bold tracking-tight">{item.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75">{item.lead}</p><a href="#poptavka" className="btn-metallic-mist mt-8 px-7 py-3.5 text-sm font-bold">Nezávazná konzultace <ArrowRight size={15} /></a></div></div></section><section className="border-y border-slate-200 bg-slate-50 py-16"><div className="site-container grid gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Přínosy pro provoz</p><h2 className="mt-3 text-slate-950">Řešení, které funguje a vydrží.</h2><ul className="mt-7 space-y-4 pl-0">{item.benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-slate-700"><CheckCircle className="shrink-0 text-[#0070F3]" size={19} />{benefit}</li>)}</ul></div><div className="grid grid-cols-2 gap-4">{item.places.map((place) => <div key={place} className="border border-slate-200 bg-white p-6"><MapPin className="text-[#0070F3]" size={20} /><p className="mt-5 font-semibold text-slate-950">{place}</p></div>)}</div></div></section><section className="relative min-h-[380px] overflow-hidden bg-slate-950"><img src={image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-40" /><div className="site-container relative py-20 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Smart řízení</p><h2 className="mt-3 max-w-2xl">Automatický provoz podle podmínek prostoru.</h2><p className="mt-5 max-w-xl text-white/70">Snímače, chytrý ventil a aplikace propojují spouštění, harmonogram i přehled spotřeby do jednoho provozního řešení.</p></div></section><UsageRecommendedProducts /><section id="poptavka" className="site-container grid gap-10 py-20 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0070F3]">Nezávazná konzultace</p><h2 className="mt-3 text-slate-950">Připravíme návrh pro váš prostor.</h2><p className="mt-4 text-slate-600">Popište nám svůj záměr. Ozveme se do 24 hodin.</p><Link to="/reference" className="mt-6 inline-block text-sm font-bold text-[#0070F3]">Ukázky realizací →</Link></div><CategoryInquiryForm category={item.title} projectScope={item.scope} /></section></main>;
}