import React from 'react';
import { motion } from 'framer-motion';
import { CloudSun, Thermometer, Timer, Waves, Radio, Gauge, Droplets, ArrowRight, Box, Wifi } from 'lucide-react';

const STEPS = [
  { Icon: Thermometer, number: '01', title: 'Senzor vyhodnotí teplotu', text: 'Po dosažení nastaveného teplotního limitu systém pokračuje ve vyhodnocení pravidel zóny.' },
  { Icon: CloudSun, number: '02', title: 'Ověří nastavené podmínky', text: 'Podle konfigurace zohlední čas, počasí nebo další připojené senzory.' },
  { Icon: Timer, number: '03', title: 'Spustí správný scénář', text: 'Řízení otevře příslušnou vodní zónu podle nastaveného časového nebo cyklického režimu.' },
  { Icon: Waves, number: '04', title: 'Řídí provoz zóny', text: 'Po skončení scénáře nebo podmínky systém příslušnou vodní zónu opět uzavře.' }
];

export default function SmartAutomationFlow() {
  const FLOW = [
    { Icon: Thermometer, label: 'SENZOR', value: '28,6 °C', note: 'teplota / podmínky' },
    { Icon: Radio, label: 'SMART ŘÍZENÍ', value: 'AUTO', note: 'vyhodnocení pravidel' },
    { Icon: Gauge, label: 'VENTIL', value: 'OTEVŘEN', note: 'řízení vodní zóny' },
    { Icon: Droplets, label: 'MLŽÍTKO', value: 'AKTIVNÍ', note: 'jemná vodní mlha' },
  ];

  return <section id="jak-to-funguje" className="scroll-mt-24 bg-background py-20 lg:py-28"><div className="mx-auto max-w-7xl px-6 lg:px-10">
    <div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div className="max-w-2xl"><p className="font-mono text-[11px] tracking-[.18em] uppercase text-secondary">Jak to funguje</p><h2 className="mt-4 font-heading text-3xl leading-tight text-foreground sm:text-4xl lg:text-5xl">Od podmínky k jemné mlze. Automaticky.</h2><p className="mt-4 text-muted-foreground">Smart řízení propojí senzory, provozní logiku a vodní zónu. Mlžení se aktivuje pouze tehdy, když jsou splněny nastavené podmínky.</p></div><p className="max-w-xl text-sm leading-relaxed text-muted-foreground lg:justify-self-end">Příklad: je-li dosažena nastavená teplota a současně běží povolené časové okno, řídicí systém aktivuje ventil příslušné zóny. Po skončení podmínky nebo scénáře se zóna automaticky uzavře.</p></div>
    <div className="mt-10 overflow-hidden rounded-[28px] border border-slate-800 bg-slate-950 p-5 shadow-xl sm:p-7"><div className="grid gap-3 md:grid-cols-4">{FLOW.map(({Icon,label,value,note},i)=><React.Fragment key={label}><div className="relative rounded-2xl border border-white/10 bg-white/[.06] p-5 text-white"><div className="flex items-center justify-between"><Icon size={24} className="text-accent"/><span className="font-mono text-[10px] tracking-[.16em] text-white/40">0{i+1}</span></div><p className="mt-8 font-mono text-[10px] tracking-[.16em] text-white/45">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-white/45">{note}</p>{i<3&&<ArrowRight size={17} className="absolute -right-[11px] top-1/2 z-10 hidden -translate-y-1/2 text-accent md:block"/>}</div></React.Fragment>)}</div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><Box size={20} className="text-secondary"/><p className="mt-3 text-sm font-semibold text-slate-900">Řídicí box</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Řídicí logika pro scénáře, čas a jednotlivé zóny.</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><Gauge size={20} className="text-secondary"/><p className="mt-3 text-sm font-semibold text-slate-900">Ventilová zóna</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Otevírá a uzavírá přívod vody podle pokynu řízení.</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><Wifi size={20} className="text-secondary"/><p className="mt-3 text-sm font-semibold text-slate-900">Vzdálená správa</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Volitelná vrstva pro podporované SMART / SMART PRO konfigurace.</p></div></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{STEPS.map(({ Icon, number, title, text }, index) => <motion.div key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="border-t-2 border-secondary pt-5"><Icon size={34} className="text-secondary" /><p className="mt-8 font-mono text-xs text-muted-foreground">{number}</p><h3 className="mt-2 font-heading text-xl text-foreground">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></motion.div>)}</div>
    <div className="mt-14 grid overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm lg:grid-cols-2"><div className="h-[280px] bg-slate-50 sm:h-[340px] lg:h-auto lg:min-h-[360px]"><img src="https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/5c4b99749_Smartmlzitka-ovladanizmobilu.jpg" alt="Smart řízení mlžného systému v mobilní aplikaci" className="h-full w-full object-contain" /></div><div className="flex flex-col justify-center p-7 sm:p-10"><p className="font-mono text-[11px] uppercase tracking-[.18em] text-secondary">Technologie v praxi</p><h3 className="mt-3 font-heading text-3xl leading-tight text-foreground">Jedno řízení. Jedna nebo více vodních zón.</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Řídicí část lze navrhnout podle rozsahu instalace – od jednoho mlžítka po několik samostatných zón. Každá zóna může mít vlastní časový režim a automatizační podmínky. Konkrétní ventilová a řídicí sestava se volí podle hydrauliky, napájení a požadovaných funkcí projektu.</p><div className="mt-6 flex flex-wrap gap-2">{['Teplota','Čas','Volitelné počasí','Volitelný pohyb','Více zón'].map(x=><span key={x} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600">{x}</span>)}</div></div></div>
  </div></section>;
}