const mistVideo = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/16e481607_Mlzitkaostev-zivaukazkamlznystrom.mov';
const auraVideo = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/8e97972ee_mlznesystemy-aura.mp4';
const urbanVideo = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/6297e30bb_Svaovnukzkazive.mov';
const installationVideo = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/2b83755fa_instalace-mlzitka-mrak1.MOV';

export const MIST_STORY_SCENES = [
  { number: '01', eyebrow: 'Tepelný ostrov', title: 'Horko mění město v prostor, kde se nechce zůstávat.', text: 'Rozpálená dlažba, ostré světlo a vzduch bez úlevy. První krok ke změně je vytvořit místo, kam lidé mohou vstoupit.', video: urbanVideo, coolingVideo: auraVideo, mode: 'heat', tags: ['Letní špička', 'Veřejný prostor'] },
  { number: '02', eyebrow: 'Aktivace mlhy', title: 'Jemný mlžný oblak spouští příjemnější mikroklima.', text: 'Nízkotlaké mlžení vytváří viditelnou mlhu, která přirozeně ochlazuje okolní vzduch bez mokré dlažby.', video: installationVideo, mode: 'mist', tags: ['Nízký tlak', 'Mlha aktivní'] },
  { number: '03', eyebrow: 'Okamžik úlevy', title: 'Úleva během vteřin.', text: 'Při vstupu do chladivé zóny se mění nejen teplota, ale i atmosféra prostoru.', video: mistVideo, mode: 'cool', tags: ['−4 až −7 °C', 'Jemné osvěžení'] },
  { number: '04', eyebrow: 'Chladivá zóna', title: 'Mikroklima, které má jasně měřitelný efekt.', text: 'Kolem konstrukce vzniká měkká aktivní zóna pro zastavení, pohyb i setkávání.', video: mistVideo, mode: 'map', tags: ['4 bar', '100–300 μm', '1,2–2,4 l/h'] },
  { number: '05', eyebrow: 'Detail technologie', title: 'Nízkotlaká atomizace v každé kapce.', text: 'Precizní tryska tvoří jemnou, viditelnou mlhu pro zvlhčení vzduchu a pohodlný pobyt venku.', video: installationVideo, mode: 'nozzle', tags: ['Viditelná mlha', 'Zvlhčení vzduchu'] },
  { number: '06', eyebrow: 'Tvar jako zážitek', title: 'Od jemného oblouku po symbol města.', text: 'Nerezové trubky lze ohýbat do tvarů Arch, Ring, Wave, Y, Semi Arch i volných organických linií. Z náčrtu, znaku nebo jediné myšlenky vytvoříme zakázkovou mlžnou skulpturu s promyšleným kotvením, vedením vody a polohou trysek.', images: ['https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/60a14cfc6_43d83e0c0_unnamed-9.png', 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/b47ae10f2_bendymlzitko.jpeg'], imageAlt: 'Zakázková mlžítka MRAK a BENDY', mode: 'forms', tags: ['Plynulé ohýbání nerezu', 'MRAK a BENDY', 'Výroba na zakázku'], actions: [{ label: 'Jak vyrábíme a ohýbáme', to: '/o-nas#vyroba-ohybani', primary: true }, { label: 'Navrhnout vlastní tvar', to: '/poptavka?produkt=Mlžítko%20na%20míru' }] },
  { number: '07', eyebrow: 'Návrh s jistotou', title: 'Doporučeno odborníky na mikroklima.', text: 'Navrhujeme systém podle místa, pohybu lidí, zdroje vody a požadovaného efektu.', video: urbanVideo, mode: 'expert', tags: ['Technický návrh', 'Instalace a servis'], actions: [{ label: 'Získat cenovou nabídku', to: '/poptavka', primary: true }, { label: 'Prohlédnout produkty', to: '/katalog' }] },
  { number: '08', eyebrow: 'Živé prostředí', title: 'Parky, náměstí, terasy i festivaly.', text: 'Mlha promění horký okamžik v důvod zůstat déle.', image: 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/1fc0ddfc5_generated_image.png', mode: 'real', tags: ['Města', 'Gastro', 'Eventy'], actions: [{ label: 'Řešení pro parky a hřiště', to: '/vyuziti/parky-hriste', primary: true }] },
];

export const HERO_IMAGE = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/3671a8607_generated_image.png';
export const HERO_VIDEO = mistVideo;