import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Droplets, MapPin, ThermometerSnowflake, Factory } from 'lucide-react';
import QuickBenefits from '@/components/home/QuickBenefits';

const HERO_IMAGE = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/3c7f3e65f_copilot_image_1784351460863.jpg';
const QUICK_LINKS = [
  { icon: Droplets, label: '5–15 μm', text: 'velikost kapének', to: '/jak-funguje-mlzeni' },
  { icon: ThermometerSnowflake, label: 'až −12 °C', text: 'pocitové ochlazení', to: '/vyhody' },
  { icon: MapPin, label: 'celá ČR', text: 'realizace po celé zemi', to: '/galerie' },
  { icon: Factory, label: 'na míru', text: 'zakázková výroba', to: '/katalog' },
];

export default function MistCinematicHero() {
  return <section className="relative min-h-[100svh] overflow-hidden bg-slate-950 text-white"><img src={HERO_IMAGE} alt="Mlžná brána v letním městském parku" fetchPriority="high" decoding="async" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,6,23,0.82)_0%,rgba(2,6,23,0.54)_42%,rgba(2,6,23,0.16)_100%)]" /><div aria-hidden="true" className="hero-light-rays"><span /><span /><span /></div><div aria-hidden="true" className="hero-mist-overlay"><span /><span /><span /></div><div className="mist-hero-glow" /><div className="relative z-10 mx-auto flex min-h-[100svh] max-w-7xl items-center px-6 py-32 lg:px-10"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-cyan">Mlžidla.cz · chlad pro veřejný prostor</p><h1 className="mt-5 font-heading text-5xl font-medium leading-[0.95] tracking-tight text-white sm:text-6xl lg:text-7xl">Osvěžení, které<br />oživí vaše město.</h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-white/80">Navrhujeme nerezová mlžítka, brány a vodní objekty, které promění horké dny v příjemný zážitek pro každého.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/mlzidla-mlzitka" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-white px-7 py-4 text-sm font-bold text-slate-950 transition hover:bg-cyan">Poznat mlžítka <ArrowRight size={17} /></Link><Link to="/poptavka" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/45 bg-white/5 px-7 py-4 text-sm font-bold text-white backdrop-blur transition hover:bg-white/15">Poptat řešení</Link></div></div><QuickBenefits className="absolute right-10 top-1/2 hidden w-[320px] -translate-y-1/2 grid-cols-2 lg:grid" compact limit={4} /></div><div className="absolute bottom-0 left-0 right-0 z-20 border-t border-white/20 bg-slate-950/45 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl overflow-x-auto px-3 py-3 lg:px-7 [&::-webkit-scrollbar]:hidden">{QUICK_LINKS.map(({ icon: Icon, label, text, to }) => <Link key={to} to={to} className="flex min-h-12 min-w-[155px] flex-1 items-center gap-3 border-r border-white/15 px-4 text-left transition hover:bg-white/10"><Icon size={23} className="shrink-0 text-cyan" /><span><b className="block text-sm text-white">{label}</b><small className="block text-[11px] text-white/65">{text}</small></span></Link>)}</div></div></section>;
}