import React, { useEffect, useState } from 'react';
import { ArrowRight, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';

export default function ReferenceSection() {
  const [projects, setProjects] = useState([]);
  useEffect(() => {base44.entities.Realizace.list().then((items) => setProjects((items || []).filter((item) => item.published !== false).slice(0, 6)));}, []);
  if (!projects.length) return null;
  return <section className="py-20 text-white lg:py-28 bg-[#244865]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="font-mono text-[11px] tracking-[.2em] uppercase text-accent">Portfolio / {projects.length} projektů</p><h2 className="mt-4 max-w-2xl font-heading text-4xl tracking-tight lg:text-6xl">Realizace, které můžete vidět.</h2></div><Link to="/reference" className="inline-flex items-center gap-2 text-sm font-bold text-accent hover:text-white">Všechny realizace <ArrowRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => { const secondary = project.gallery_urls?.find((url) => url && url !== project.image_url) || project.image_url; return <Link key={project.id} to={`/reference/${project.id}`} className="group overflow-hidden rounded-[22px] border border-white/15 bg-white/[.04] shadow-lg transition-all duration-500 hover:-translate-y-2 hover:border-cyan/40 hover:shadow-2xl"><div className="relative aspect-[4/3] overflow-hidden"><img src={project.image_url} alt={project.name} className="absolute inset-0 h-full w-full object-cover transition-all duration-700 group-hover:scale-[1.04] group-hover:opacity-0"/><img src={secondary} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full scale-105 object-cover opacity-0 transition-all duration-700 group-hover:scale-100 group-hover:opacity-100"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-4 left-5 right-5"><div className="flex items-center justify-between font-mono text-[9px] tracking-widest uppercase text-white/60"><span className="inline-flex items-center gap-1.5"><MapPin size={11}/>{project.location}</span><span>{project.year}</span></div><h3 className="mt-2 font-heading text-2xl leading-tight">{project.name}</h3></div></div><div className="p-5"><p className="text-sm leading-6 text-white/60">{project.product_used || 'Zakázkové mlžicí řešení'}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-accent transition-all group-hover:gap-3">Zobrazit realizaci <ArrowRight size={14}/></span></div></Link>})}</div></div></section>;
}