import React, { useEffect, useState } from 'react';
import { AppWindow, CalendarClock, CloudSun, Play, ShieldCheck, Smartphone, Thermometer, Wifi } from 'lucide-react';

const PHOTO_URL = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/b68df5d31_Gemini_Generated_Image_5gclad5gclad5gcl.png';
const VIDEO_URL = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/5e7a7f5d5_mlzidlospiralavakci-video.MOV';
const features = [{ icon: Smartphone, title: 'Aplikace', text: 'Přehled zón a spotřeby.' }, { icon: Thermometer, title: 'Senzory', text: 'Reakce na teplotu a vlhkost.' }, { icon: CalendarClock, title: 'Harmonogram', text: 'Automatické provozní cykly.' }, { icon: Wifi, title: 'Smart ventil', text: 'Přesné řízení každé zóny.' }];

export default function SmartMicroclimateHero() {
  const [playing, setPlaying] = useState(false); const [active, setActive] = useState(0);
  useEffect(() => { if (!playing) return undefined; const timer = window.setInterval(() => setActive((current) => (current + 1) % features.length), 1400); return () => window.clearInterval(timer); }, [playing]);
  return <section className="relative overflow-hidden bg-slate-950 py-20 text-white lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,rgba(34,211,238,.16),transparent_30%),linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:auto,36px_36px,36px_36px]" /><div className="site-container relative"><div className="mb-12 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan">Smart systém HolmTec</p><h2 className="mt-3 font-heading text-4xl font-medium tracking-tight lg:text-5xl">Chytrá správa řízení mlžítek.</h2><p className="mt-5 text-lg text-white/65">Účinné ochlazení pro města, terasy a veřejný prostor.</p></div><div className="grid gap-6 lg:grid-cols-[.8fr_1.15fr_.8fr] lg:items-center"><div className="space-y-3">{features.slice(0, 2).map((item, index) => <FeatureCard key={item.title} item={item} active={playing && active === index} />)}</div><div className="relative overflow-hidden rounded-2xl border border-cyan/30 bg-black shadow-2xl shadow-cyan/10">{playing ? <video src={VIDEO_URL} autoPlay muted loop playsInline className="aspect-[4/3] w-full object-cover" /> : <><img src={PHOTO_URL} alt="Mlžná brána v provozu" className="aspect-[4/3] w-full object-cover" /><div className="absolute inset-0 bg-slate-950/20" /></>}<button onClick={() => setPlaying((value) => !value)} className="absolute inset-0 flex items-center justify-center"><span className="flex h-20 w-20 items-center justify-center rounded-full border border-cyan/60 bg-slate-950/70 text-cyan shadow-[0_0_36px_rgba(34,211,238,.5)] transition hover:scale-110">{playing ? <AppWindow size={25} /> : <Play size={28} fill="currentColor" />}</span></button><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/90 to-transparent p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan">Živá ukázka</p><p className="mt-1 text-lg font-semibold">Mlžná brána se smart řízením</p></div></div><div className="space-y-3">{features.slice(2).map((item, index) => <FeatureCard key={item.title} item={item} active={playing && active === index + 2} />)}<div className="flex items-center gap-3 px-3 pt-2 text-xs text-white/50"><ShieldCheck size={17} className="text-cyan" />Aktivní zóny se zvýrazňují podle provozu.</div></div></div></div></section>;
}

function FeatureCard({ item, active }) { const Icon = item.icon; return <article className={`relative border-l-2 p-4 transition-all duration-500 ${active ? 'border-cyan bg-cyan/15 shadow-[0_0_22px_rgba(34,211,238,.14)]' : 'border-white/15 bg-white/[.035]'}`}><span className={`absolute -left-[5px] top-1/2 h-2 w-2 -translate-y-1/2 rounded-full ${active ? 'bg-cyan shadow-[0_0_12px_#22d3ee]' : 'bg-white/30'}`} /><div className="flex gap-3"><Icon size={21} className="shrink-0 text-cyan" /><div><h3 className="text-base font-semibold">{item.title}</h3><p className="mt-1 text-sm text-white/55">{item.text}</p></div></div></article>; }