import React, { useEffect, useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';

export default function RelatedProductsSection({ productUsed }) {
  const [products, setProducts] = useState([]);
  useEffect(() => { base44.entities.Product.list().then((items) => { const sorted = [...items].sort((a, b) => Number(b.featured) - Number(a.featured)); const matching = productUsed ? sorted.filter((item) => item.name.toLowerCase().includes(productUsed.toLowerCase()) || productUsed.toLowerCase().includes(item.name.toLowerCase())) : []; setProducts([...matching, ...sorted.filter((item) => !matching.includes(item))].slice(0, 3)); }); }, [productUsed]);
  if (!products.length) return null;
  return <section className="border-y border-slate-200 bg-slate-50 py-14 lg:py-16"><div className="mx-auto max-w-7xl px-6 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Vhodné pro váš projekt</p><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><h2 className="font-heading text-3xl font-medium text-slate-900">Prohlédněte si mlžítka</h2><Link to="/mlzidla-mlzitka" className="inline-flex items-center gap-2 text-sm font-bold text-slate-700 hover:text-slate-950">Všechny produkty <ArrowRight size={15} /></Link></div><div className="mt-8 grid gap-4 md:grid-cols-3">{products.map((product) => <Link key={product.id} to={`/produkt/${product.slug}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-lg"><div className="aspect-[16/9] bg-slate-200">{product.image_url && <img src={product.image_url} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />}</div><div className="p-5"><h3 className="font-heading text-xl font-medium text-slate-900">{product.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-slate-500">{product.short_description || 'Designové řešení mlžení navržené pro veřejný prostor.'}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-slate-800">Detail produktu <ArrowRight size={14} /></span></div></Link>)}</div></div></section>;
}