import React, { useState } from 'react';
import { Calculator, Droplets } from 'lucide-react';
import { Link } from 'react-router-dom';
import OperatingCostResults from '@/components/produkt/OperatingCostResults';
import { getNozzleCount, HOURS_PER_DAY, WATER_RATE_WITH_SEWER } from '@/lib/operatingCosts';

export default function NozzleCostCalculator({ product }) {
  const [seasonDays, setSeasonDays] = useState(120);
  const nozzles = getNozzleCount(product);
  return <section className="border-y border-slate-200 bg-slate-50 py-16 lg:py-20"><div className="site-container"><div className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="content-eyebrow mb-3 flex items-center gap-2"><Calculator size={16} /> Spočítat provozní náklady</p><h2 className="content-title text-3xl">Kolik stojí provoz modelu {product.name}.</h2><p className="content-lead mt-3">Výpočet vychází z {nozzles} {nozzles === 1 ? 'trysky' : 'trysek'}, tlaku 4 bar a ceny {WATER_RATE_WITH_SEWER} Kč/m³ včetně vodného a stočného.</p></div><label className="w-full max-w-xs text-sm font-semibold text-slate-800">Délka letní sezóny: {seasonDays} dní<input type="range" min="30" max="150" step="5" value={seasonDays} onChange={(event) => setSeasonDays(Number(event.target.value))} className="mt-3 w-full accent-slate-950" /><span className="mt-1 flex justify-between text-xs font-normal text-slate-400"><span>30 dní</span><span>{seasonDays * HOURS_PER_DAY} hodin</span><span>150 dní</span></span></label></div><OperatingCostResults nozzles={nozzles} seasonDays={seasonDays} /><div className="mt-7 flex flex-wrap gap-3"><Link to={`/poptavka?produkt=${encodeURIComponent(product.name)}`} className="btn-metallic-mist px-6 py-3 text-sm font-bold"><Droplets size={15} /> Poptat toto řešení</Link><Link to="/kalkulacka" className="inline-flex items-center rounded-full border border-slate-300 px-6 py-3 text-sm font-bold text-slate-800">Otevřít úplnou kalkulačku</Link></div></div></section>;
}