const urbanPhoto = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/4737b1d8d_5b1b2bcc1b140ee76c8402a1e6313b8f.jpg';
const techPhoto = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/3c7f3e65f_copilot_image_1784351460863.jpg';
const mistPhoto = 'https://media.base44.com/images/public/6a3ee88c10959cd3588c4d68/97adcdb67_file_000000001abc8243a41e16d7f22e87b8.png';
export const defaultHeroVideo = 'https://media.base44.com/videos/public/6a3ee88c10959cd3588c4d68/2c401631b_ukazkamlhy-zivaukazka002.mov';

const createCategory = (title, lead, places, benefits, image, scope = 'urban') => ({ title, lead, places, benefits, image, scope });

export const usageCategories = {
  'mesta-obce': createCategory('Mlžítka pro města a obce', 'Ochlazení rozpálených náměstí, pěších zón a míst, kde se lidé setkávají.', ['Náměstí a pěší zóny', 'Zastávky MHD', 'Veřejná prostranství', 'Sportovní areály'], ['Ochlazení okolí až o 9 °C', 'Smart řízení podle teploty a pohybu', 'Zakázková výroba dle identity místa'], urbanPhoto),
  'parky-hriste': createCategory('Mlžítka pro parky a hřiště', 'Bezpečné osvěžení pro rodiny, děti a návštěvníky zelených ploch.', ['Dětská hřiště', 'Zámecké parky', 'Městská zeleň', 'Sportovní zóny'], ['Potravinářská nerez bez chemie', 'Mikrokapky bez mokrého povrchu', 'Odolné řešení pro veřejný provoz'], urbanPhoto),
  'skoly-skolky-deti': createCategory('Mlžítka pro školy, školky a děti', 'Příjemnější venkovní výuka a bezpečná hra i v tropických dnech.', ['Školní dvory', 'Mateřské školy', 'Dětské skupiny', 'Volnočasové areály'], ['Bezpečné osvěžení bez chemie', 'Automatický časový režim', 'Robustní konstrukce pro děti'], urbanPhoto),
  'domovy-senioru': createCategory('Mlžítka pro domovy seniorů', 'Teplotní komfort pro citlivou skupinu obyvatel během vln veder.', ['Zahrady domovů', 'Altány', 'Odpočinkové terasy', 'Návštěvní zóny'], ['Méně tepelného stresu', 'Tichý automatický provoz', 'Komfort bez šoku z klimatizace'], urbanPhoto),
  hotely: createCategory('Mlžítka pro hotely a restaurace', 'Komfort, který prodlouží pobyt hostů na terase i během horkých dnů.', ['Hotelové terasy', 'Restaurace', 'Atria', 'Vstupní zóny'], ['Vyšší atraktivita venkovního posezení', 'Diskrétní designové provedení', 'Snadné řízení z aplikace'], urbanPhoto, 'private'),
  'wellness-terasy': createCategory('Mlžítka pro wellness terasy', 'Jemná mlha pro komfortní přechod mezi saunou, bazénem a odpočinkem.', ['Saunové světy', 'Spa terasy', 'Bazénové zóny', 'Relaxační zahrady'], ['Příjemné ochlazení po sauně', 'Prémiový zážitek pro hosty', 'Řízená hygiena vody'], mistPhoto, 'private'),
  koupaliste: createCategory('Mlžítka pro koupaliště a aquaparky', 'Chladivé zóny pro intenzivní letní provoz u vody.', ['Vstupy a fronty', 'Bazénové plochy', 'Dětské zóny', 'Občerstvení'], ['Osvěžení bez kluzkého povrchu', 'Provozní automatizace', 'Odolná nerezová konstrukce'], urbanPhoto),
  architekti: createCategory('Mlžítka pro architekty', 'Mlha jako funkční materiál návrhu a výrazný prvek veřejného prostoru.', ['Nové stavby', 'Revitalizace', 'Veřejný parter', 'Autorské instalace'], ['Návrh na míru projektu', 'Nerezová konstrukce', 'Technická podpora architektům'], techPhoto),
  komercni: createCategory('Mlžítka pro komerční prostory', 'Komfortní prostředí, které podporuje návštěvnost i plynulý provoz.', ['Retail parky', 'Obchodní centra', 'Showroomy', 'Firemní areály'], ['Komfort návštěvníků', 'Automatický provoz', 'Měřitelné statistiky spotřeby'], techPhoto, 'industrial'),
  eventy: createCategory('Mobilní mlžítka pro eventy a festivaly', 'Rychle připravené osvěžení pro davy, koncerty a letní akce.', ['Festivaly', 'Sportovní akce', 'Firemní dny', 'Dočasné instalace'], ['Rychlá instalace', 'Možnost pronájmu', 'Mobilní provoz bez zásahu do místa'], urbanPhoto, 'event'),
  'outdoor-zahrady': createCategory('Mlžítka pro zahrady a outdoor', 'Nenápadné ochlazení soukromých teras, pergol a zahradních posezení.', ['Terasy', 'Pergoly', 'Bazény', 'Zahradní kuchyně'], ['Pohodlí doma', 'Čisté začlenění do prostoru', 'Jednoduché ovládání'], urbanPhoto, 'private'),
  'art-instalace': createCategory('Mlžítka pro art instalace', 'Zakázkové mlžné skulptury jako silný zážitkový prvek v prostoru.', ['Galerie pod širým nebem', 'Kulturní areály', 'Městské slavnosti', 'Autorské projekty'], ['Individuální návrh', 'Nerezové tvarování', 'Přesné scénické řízení'], techPhoto),
};