export const usageAudienceData = {
  'mesta-obce': { audience: 'Pro starosty, místostarosty, městské architekty a správce veřejného prostoru.', priorities: ['Tepelný komfort obyvatel během veder', 'Bezpečný a předvídatelný provoz', 'Řešení vhodné do rozpočtu i etapizace'], offer: ['Místní šetření a návrh umístění', 'Mlžné brány GATE a LINEA pro frekventované zóny', 'Designová mlžítka a Smart řízení pro náměstí a parky'] },
  'parky-hriste': { audience: 'Pro správce zeleně, městské části, developery a provozovatele hřišť.', priorities: ['Osvěžení návštěvníků v horku', 'Odolné provedení pro každodenní provoz', 'Časové a pohybové spouštění'], offer: ['Návrh bezpečné zóny podle pohybu lidí', 'Samostatná designová mlžítka', 'Sezónní servis a zazimování'] },
  'skoly-skolky-deti': { audience: 'Pro ředitele škol, zřizovatele, projektanty a správce školních areálů.', priorities: ['Příjemnější venkovní výuka a hra', 'Kontrolovaný provoz v určeném čase', 'Robustní konstrukce bez ostrých hran'], offer: ['Posouzení školního dvora nebo zahrady', 'Vhodný počet trysek a bezpečné kotvení', 'Jednoduché ovládání pro personál'] },
  'domovy-senioru': { audience: 'Pro vedení domovů, obce, sociální služby a správce pobytových zařízení.', priorities: ['Snížení tepelné zátěže citlivých klientů', 'Tichá atmosféra pro klid a odpočinek', 'Snadné ovládání bez nároků na obsluhu'], offer: ['Návrh klidové mlžné zóny v zahradě', 'Designová mlžítka s jemným zvukem vody', 'Automatické spouštění podle teploty'] },
  hotely: { audience: 'Pro hoteliéry, restauratéry, facility manažery a provozovatele teras.', priorities: ['Delší a příjemnější pobyt hostů venku', 'Čistý design odpovídající značce', 'Provoz podle obsazenosti a počasí'], offer: ['Návrh zón bez narušení obsluhy', 'Designové modely pro terasy a vstupy', 'Smart ovládání a provozní scénáře'] },
  'wellness-terasy': { audience: 'Pro wellness centra, spa hotely, saunové světy a bazénové provozy.', priorities: ['Plynulý přechod mezi teplem a odpočinkem', 'Prémiový smyslový zážitek', 'Kontrolovaný a hygienický vodní okruh'], offer: ['Návrh relaxační mlžné zóny', 'Architektonická mlžítka na míru', 'Provozní a servisní plán'] },
  koupaliste: { audience: 'Pro provozovatele koupališť, aquaparků a sportovních areálů.', priorities: ['Osvěžení front a odpočinkových zón', 'Odolnost při vysoké návštěvnosti', 'Rychlé řízení více provozních míst'], offer: ['Mlžné brány pro vstupy a pěší trasy', 'Samostatná mlžítka do odpočinkových zón', 'Automatizace podle času a teploty'] },
  architekti: { audience: 'Pro architekty, krajinářské architekty, projektanty a designéry.', priorities: ['Technicky proveditelný autorský návrh', 'Podklady pro koordinaci profesí', 'Materiálové a rozměrové varianty'], offer: ['Konzultace konceptu a technických detailů', 'Výkresy, specifikace a podklady do projektu', 'Zakázkové ohýbání a výroba nerezu'] },
  komercni: { audience: 'Pro developery, retail, facility management a vlastníky firemních areálů.', priorities: ['Komfort návštěvníků a zaměstnanců', 'Reprezentativní vstupní či odpočinková zóna', 'Měřitelná a řízená spotřeba vody'], offer: ['Návrh podle návštěvnosti a provozních hodin', 'Mlžné brány i designová mlžítka', 'Smart scénáře a vzdálené ovládání'] },
  eventy: { audience: 'Pro produkce, agentury, pořadatele festivalů a sportovních akcí.', priorities: ['Rychlá instalace bez zásahu do areálu', 'Osvěžení velkého počtu návštěvníků', 'Spolehlivost po celou dobu akce'], offer: ['Krátkodobý pronájem vhodné sestavy', 'Doprava, instalace a technická podpora', 'Branding a rozmístění podle toku návštěvníků'] },
  'outdoor-zahrady': { audience: 'Pro majitele zahrad, zahradní architekty a realizační firmy.', priorities: ['Komfort terasy a zahradního posezení', 'Nenápadné začlenění do zahrady', 'Jednoduchý sezónní provoz'], offer: ['Výběr vhodného designového modelu', 'Návrh kotvení a přívodu vody', 'Manuální nebo chytré ovládání'] },
  'art-instalace': { audience: 'Pro umělce, kurátory, kulturní instituce a městské investory.', priorities: ['Silný vizuální a smyslový účinek', 'Autorský tvar a scénografie mlhy', 'Bezpečné technické řešení'], offer: ['Společný vývoj konceptu a prototypu', 'Zakázkové tvarování nerezové konstrukce', 'Programovatelné scénáře a technická realizace'] },
};